import { PoolQuestion } from './types';

export const ACTIVITY_QUESTIONS: PoolQuestion[] = [
  {
    id: 'a1',
    genre: 'activity',
    questionText: '休日の午後、一番ワクワクする過ごし方は？',
    description: '自分の好きなことを思いっきり楽しむ時間！',
    options: [
      { id: 'a1_park', label: '友達と公園でインラインスケートや自転車・鬼ごっこ！', emoji: '🚲', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a1_cafe', label: '可愛いカフェやクレープ屋さんでおいしいおやつタイム！', emoji: '🥞', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'a1_game', label: 'オンラインゲームでフレンドと対戦やボイスチャット！', emoji: '🎮', categoryWeights: { 'クール＆ストリート': 2, 'サブカル＆Y2K': 2 }, secretTag: 'cyber' },
      { id: 'a1_mall', label: 'ショッピングモールでファンシー雑貨や服を見て回る！', emoji: '🛍️', categoryWeights: { 'トレンド＆アイドル': 3 } },
    ],
  },
  {
    id: 'a2',
    genre: 'activity',
    questionText: 'YouTubeや動画サイトでよく見るジャンルは？',
    description: '画面を見ながらついつい笑っちゃうチャンネル！',
    options: [
      { id: 'a2_dance', label: '流行りのダンス動画・踊ってみた・Shortsチャレンジ', emoji: '💃', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
      { id: 'a2_game', label: 'マイクラやロブロックス・スプラのゲーム実況！', emoji: '👾', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'a2_vlog', label: '小中学生YouTuberのルーティンやお部屋紹介・筆箱紹介', emoji: '🏠', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'a2_animal', label: 'もふもふ子猫やワンちゃんの癒やしショート動画', emoji: '🐱', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'a2_sports', label: 'スポーツの神技スーパープレイ集やスケボー動画', emoji: '🛹', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
    ],
  },
  {
    id: 'a3',
    genre: 'activity',
    questionText: '自分のお部屋を模様替えするなら、どんなテイストにする？',
    description: '自分だけの大好きが詰まったお城！',
    options: [
      { id: 'a3_pastel', label: 'ホワイト家具にピンクやラベンダーのクッションで韓国風', emoji: '🛏️', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'a3_neon', label: 'ゲーミングLEDライトを光らせたサイバーハイテク部屋', emoji: '💡', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'a3_nature', label: '観葉植物や木製ラックを置いたナチュラル癒やし空間', emoji: '🪴', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'a3_poster', label: '推しのポスターやグッズをきれいに飾る専用コーナー', emoji: '🖼️', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'a3_antique', label: 'アンティークランプや古書風ノートを並べたレトロ部屋', emoji: '🕰️', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 'a4',
    genre: 'activity',
    questionText: 'テーマパークに行ったら、真っ先に乗るアトラクションは？',
    description: 'パークのゲートをくぐった瞬間の高揚感！',
    options: [
      { id: 'a4_coaster', label: 'スピード感MAXの絶叫ジェットコースター！', emoji: '🎢', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a4_carousel', label: '優雅に音楽が流れる2階建てメリーゴーラウンド', emoji: '🎠', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'a4_dark', label: '3Dゴーグルをつけて敵を撃つシューティングライド', emoji: '🔫', categoryWeights: { 'クール＆ストリート': 2, 'サブカル＆Y2K': 2 }, secretTag: 'cyber' },
      { id: 'a4_castle', label: 'お城の中でプリンセスや魔法の世界を体験するツアー', emoji: '🏰', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'magical' },
    ],
  },
  {
    id: 'a5',
    genre: 'activity',
    questionText: 'もしペットを飼うなら、どの子と暮らしてみたい？',
    description: '毎日の生活を共にする最高の相棒！',
    options: [
      { id: 'a5_dog', label: '一緒にボール投げやフリスビーができる元気なワンちゃん', emoji: '🐶', categoryWeights: { 'スポーティ＆アクティブ': 2, 'アニマル＆マスコット': 2 } },
      { id: 'a5_cat', label: '気まぐれに甘えてゴロゴロ喉を鳴らすふわふわ猫ちゃん', emoji: '🐱', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'a5_rabbit', label: 'お鼻をひくひくさせる白うさぎやモルモット', emoji: '🐰', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'a5_bird', label: 'おしゃべりができるカラフルなインコや文鳥', emoji: '🦜', categoryWeights: { 'シーズン＆ネイチャー': 3 } },
      { id: 'a5_pegasus', label: '虹の空を飛べる伝説のペガサスやユニコーン！', emoji: '🦄', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'a6',
    genre: 'activity',
    questionText: 'カラオケに行ったら歌いたい曲の雰囲気は？',
    description: 'マイクを握って気持ちよく熱唱！',
    options: [
      { id: 'a6_dance', label: 'みんなでサビの振り付けを踊れる最新のアイドルソング！', emoji: '💃', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
      { id: 'a6_anime', label: 'テンションが爆上がりする疾走感あるアニメ主題歌！', emoji: '🔥', categoryWeights: { 'スポーティ＆アクティブ': 2, 'サブカル＆Y2K': 2 } },
      { id: 'a6_ballad', label: 'しっとり心に響く優しいメロディのバラード', emoji: '🌙', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'a6_vocaloid', label: '超早口で電子音がピコピコ鳴るボカロ・打ち込み曲！', emoji: '🎧', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
    ],
  },
  {
    id: 'a7',
    genre: 'activity',
    questionText: '習い事をするなら、どれに一番興味がある？',
    description: '放課後のスキルアップ！',
    options: [
      { id: 'a7_dance', label: 'ヒップホップやK-POPのダンスレッスン！', emoji: '👟', categoryWeights: { 'トレンド＆アイドル': 3, 'クール＆ストリート': 1 } },
      { id: 'a7_swim', label: 'スイミングや体操・ボルダリング！', emoji: '🏊‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a7_piano', label: 'ピアノやバイオリンなどのクラシック楽器', emoji: '🎹', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'a7_prog', label: 'プログラミングやイラスト・デジタル制作！', emoji: '💻', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
    ],
  },
  {
    id: 'a8',
    genre: 'activity',
    questionText: '旅行に行くなら、どんな場所に行ってみたい？',
    description: '家族やお友達と行く夢のバカンス！',
    options: [
      { id: 'a8_sea', label: 'エメラルドグリーンの南の島でマリンスポーツ！', emoji: '🏝️', categoryWeights: { 'スポーティ＆アクティブ': 2, 'シーズン＆ネイチャー': 2 } },
      { id: 'a8_snow', label: '雪景色が広がる銀世界のスキーリゾート！', emoji: '⛷️', categoryWeights: { 'シーズン＆ネイチャー': 3 } },
      { id: 'a8_paris', label: 'お城や美術館がたくさんあるヨーロッパの街並み', emoji: '🏰', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
      { id: 'a8_space', label: '宇宙ステーションから地球を眺める宇宙旅行！', emoji: '🚀', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
    ],
  },
  {
    id: 'a9',
    genre: 'activity',
    questionText: 'お小遣いでカプセルトイ（ガチャガチャ）を回すなら？',
    description: '何が出るかハンドルを回すワクワク！',
    options: [
      { id: 'a9_mini', label: '本物そっくりのミニチュアお菓子・ファミレスメニュー', emoji: '🧁', categoryWeights: { 'スウィート＆ガーリー': 2, 'アニマル＆マスコット': 1 } },
      { id: 'a9_ring', label: '魔法少女のステッキや宝石がついたリングカプセル', emoji: '💍', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'magical' },
      { id: 'a9_retro', label: '昔の公衆電話やレトロゲーム機のリアルフィギュア', emoji: '📟', categoryWeights: { 'クラシック＆レトロ': 2, 'サブカル＆Y2K': 2 } },
      { id: 'a9_soft', label: 'むにむに触って気持ちいいスクイーズ・マスコット', emoji: '🍞', categoryWeights: { 'アニマル＆マスコット': 3 } },
    ],
  },
  {
    id: 'a10',
    genre: 'activity',
    questionText: 'お友達とお泊まり会をしたら、夜何をして遊ぶ？',
    description: '夜更かしが特別に許される日！',
    options: [
      { id: 'a10_pillow', label: 'パジャマ姿でまくら投げ大会＆大爆笑！', emoji: '💥', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a10_beauty', label: 'フェイスパックやヘアアレンジごっこでおしゃれ研究', emoji: '🪞', categoryWeights: { 'トレンド＆アイドル': 3, 'スウィート＆ガーリー': 1 } },
      { id: 'a10_scary', label: '部屋を暗くして懐中電灯で怖い話大会！', emoji: '🔦', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'a10_star', label: 'ベランダに出て毛布にくるまりながら星空観測', emoji: '🌟', categoryWeights: { 'ファンタジー＆ドリーム': 2, 'ナチュラル＆ピュア': 2 }, secretTag: 'cosmic' },
    ],
  },
  {
    id: 'a11',
    genre: 'activity',
    questionText: 'プリクラを撮るときの落書きやスタンプは？',
    description: 'シールに印刷される最高の記念！',
    options: [
      { id: 'a11_simple', label: '日付と名前だけ！シンプルで盛れる文字書き', emoji: '🖊️', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'a11_stamp', label: 'うさ耳や猫耳スタンプ、キラキラハートで画面いっぱいに！', emoji: '🐱', categoryWeights: { 'スウィート＆ガーリー': 2, 'アニマル＆マスコット': 2 }, secretTag: 'magical' },
      { id: 'a11_funny', label: 'おもしろい顔や変顔をしてネタ系スタンプで爆笑！', emoji: '🤪', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a11_y2k', label: 'ガラケー風フォントや平成レトロなキラキラデコ！', emoji: '📱', categoryWeights: { 'サブカル＆Y2K': 3 } },
    ],
  },
  {
    id: 'a12',
    genre: 'activity',
    questionText: 'ゲームでキャラクターを作るとき、どんな見た目にする？',
    description: 'アバターメイキングのこだわり！',
    options: [
      { id: 'a12_sporty', label: 'スニーカーにキャップをかぶった快活なアスリート風', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a12_pink', label: 'ピンクのツインテールにお姫さまドレスのラブリー系', emoji: '💖', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'a12_cyber', label: '光るスーツやゴーグルをつけたサイバー戦士風', emoji: '🤖', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'a12_witch', label: 'ローブをまとったミステリアスな魔法使い風', emoji: '🧙‍♀️', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 'a12_queen', label: '黄金の冠とマントを身につけた古代の女王風', emoji: '👑', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 'a13',
    genre: 'activity',
    questionText: 'スマホやタブレットでよく遊ぶアプリは？',
    description: '画面をタップして楽しむお気に入り！',
    options: [
      { id: 'a13_rhythm', label: '音楽に合わせてノーツを叩くリズムゲーム・音ゲー！', emoji: '🥁', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'a13_puzzle', label: '同じ色のピースを消していく爽快パズルゲーム！', emoji: '🧩', categoryWeights: { 'ナチュラル＆ピュア': 2 } },
      { id: 'a13_action', label: 'ステージを駆け抜ける障害物ランアクションゲーム！', emoji: '🏃', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a13_dress', label: 'お洋服やメイクを自由に着せ替えるファッションゲーム！', emoji: '👗', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
  {
    id: 'a14',
    genre: 'activity',
    questionText: '推し（好きなアイドル・キャラ）を応援するなら？',
    description: '推し活でテンションMAX！',
    options: [
      { id: 'a14_penlight', label: '推しカラーのペンライトを振ってライブで盛り上がる！', emoji: '🪄', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
      { id: 'a14_goods', label: '推しの缶バッジやアクスタをバッグにつけて一緒にお出かけ！', emoji: '📛', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'a14_draw', label: 'ファンアートを描いたりバースデーを全力でお祝い！', emoji: '🎂', categoryWeights: { 'スウィート＆ガーリー': 2, 'サブカル＆Y2K': 2 } },
      { id: 'a14_quiet', label: '動画や音楽をじっくり聴いて心の中で静かに愛でる！', emoji: '🎧', categoryWeights: { 'ナチュラル＆ピュア': 2, 'クール＆ストリート': 2 } },
    ],
  },
  {
    id: 'a15',
    genre: 'activity',
    questionText: 'お花屋さんに行ったら、どのお花に惹かれる？',
    description: '色とりどりの素敵な花たち！',
    options: [
      { id: 'a15_sunflower', label: '元気いっぱいに太陽へ向かって咲くヒマワリ！', emoji: '🌻', categoryWeights: { 'スポーティ＆アクティブ': 2, 'シーズン＆ネイチャー': 2 } },
      { id: 'a15_tulip', label: 'パステルピンクやイエローのコロンとしたチューリップ', emoji: '🌷', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'a15_lavender', label: '香りがよくて落ち着く紫のラベンダーやカスミソウ', emoji: '🪻', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'a15_blue_rose', label: '夜空色に染められた奇跡の青いバラ！', emoji: '💙', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
    ],
  },
  {
    id: 'a16',
    genre: 'activity',
    questionText: '秋のお祭りで屋台を巡るなら、一番買いたいものは？',
    description: '提灯の明かりと太鼓の音が響く夜！',
    options: [
      { id: 'a16_candy', label: 'キラキラ光るりんご飴やりんご飴の進化系いちご飴！', emoji: '🍎', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'a16_mask', label: 'お気に入りのキャラクターお面をつけて変身気分！', emoji: '👺', categoryWeights: { 'アニマル＆マスコット': 2, 'サブカル＆Y2K': 2 } },
      { id: 'a16_shoot', label: '景品を狙って真剣勝負する射的ゲーム！', emoji: '🎯', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a16_goldfish', label: 'ポイを破らないようにそっとすくう金魚すくい！', emoji: '🐟', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'a17',
    genre: 'activity',
    questionText: '博物館や科学館で一番ワクワクする展示コーナーは？',
    description: '時空を超えた大発見の世界！',
    options: [
      { id: 'a17_dino', label: '迫力満点の巨大恐竜の骨格標本！', emoji: '🦖', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a17_space', label: 'ロケットエンジンや宇宙服の体験コーナー！', emoji: '🚀', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
      { id: 'a17_egypt', label: '古代エジプトのピラミッドや黄金のファラオマスク！', emoji: '🏺', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
      { id: 'a17_future', label: 'AIロボットと会話したり触れ合える未来技術ゾーン！', emoji: '🤖', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
    ],
  },
  {
    id: 'a18',
    genre: 'activity',
    questionText: '自分で写真を撮るなら、どんな被写体が好き？',
    description: 'シャッターを切るワクワク！',
    options: [
      { id: 'a18_friends', label: '友達とふざけ合って笑っている自然な表情！', emoji: '👭', categoryWeights: { 'スポーティ＆アクティブ': 2, 'トレンド＆アイドル': 2 } },
      { id: 'a18_sky', label: '夕焼け空や虹、雲の形が綺麗な空の写真', emoji: '🌈', categoryWeights: { 'シーズン＆ネイチャー': 3 }, secretTag: 'unicorn' },
      { id: 'a18_sweets', label: 'カフェのおしゃれなスイーツや可愛い小物', emoji: '🧁', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'a18_animal', label: '道端で出会った野良猫やすずめたち', emoji: '🐾', categoryWeights: { 'アニマル＆マスコット': 3 } },
    ],
  },
  {
    id: 'a19',
    genre: 'activity',
    questionText: 'お風呂に入るときの入浴剤はどんなのが好き？',
    description: '1日の疲れを癒やすバスタイム！',
    options: [
      { id: 'a19_toy', label: '中からマスコットが出てくるバスボール！', emoji: '🫧', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'a19_sparkle', label: 'お湯がキラキララメ色やピンクに染まるバスボム', emoji: '💖', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'a19_herb', label: '森のひのきやミントのすっきりハーブ湯', emoji: '🌿', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'a19_bubble', label: '泡がもこもこ立ち上るバブルバス！', emoji: '🛁', categoryWeights: { 'トレンド＆アイドル': 2 } },
    ],
  },
  {
    id: 'a20',
    genre: 'activity',
    questionText: '夜眠る前、どんなことを考えて眠りにつく？',
    description: '夢の世界へ旅立つ前のひととき！',
    options: [
      { id: 'a20_next_day', label: '「明日も友達とたくさん遊ぶぞ！」とワクワク', emoji: '☀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'a20_dream', label: 'お気に入りの物語や魔法の世界の続きを空想する', emoji: '🌙', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
      { id: 'a20_peace', label: 'ふかふかのお布団の温もりを感じてすやすやリラックス', emoji: '😴', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'a20_galaxy', label: '宇宙の果てや星座の神秘に思いを馳せる', emoji: '🌌', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
    ],
  },
];
