import { PoolQuestion } from './types';

export const FASHION_QUESTIONS: PoolQuestion[] = [
  {
    id: 'f1',
    genre: 'fashion',
    questionText: '学校に着ていくなら、どんなボトムスが好き？',
    description: '普段よくはく、または一番お気に入りのスタイルを選んでね',
    options: [
      { id: 'f1_short', label: '動きやすいショートパンツ・スカパン', emoji: '🩳', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f1_skirt', label: 'ひらひら揺れるプリーツスカート', emoji: '👗', categoryWeights: { 'スウィート＆ガーリー': 3, 'トレンド＆アイドル': 1 } },
      { id: 'f1_denim', label: 'こなれ感のあるストレートデニム', emoji: '👖', categoryWeights: { 'クール＆ストリート': 3, 'クラシック＆レトロ': 1 } },
      { id: 'f1_linen', label: 'やさしい肌触りのコットン・リネンワイドパンツ', emoji: '🌿', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'f2',
    genre: 'fashion',
    questionText: '好きなTシャツ・トップスのプリントは？',
    description: '見つけるとつい欲しくなっちゃうデザインは？',
    options: [
      { id: 'f2_sport', label: 'カレッジ風の英字ロゴ・スポーティライン', emoji: '⚡', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f2_ribbon', label: 'リボン・フリル・小さなお花柄', emoji: '🎀', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'f2_cool', label: 'クールなモノトーン・フォトプリント', emoji: '📷', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'f2_animal', label: 'ゆるかわアニマルイラスト・ワンポイント', emoji: '🐻', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'f2_y2k', label: 'ネオンカラーやグラデーション・Y2Kロゴ', emoji: '💿', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
    ],
  },
  {
    id: 'f3',
    genre: 'fashion',
    questionText: '靴下（ソックス）を選ぶときのこだわりは？',
    description: '足元のコーデにもこだわりたい！',
    options: [
      { id: 'f3_line', label: 'スニーカーに似合うライン入りリブソックス', emoji: '🧦', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f3_lace', label: 'レースやフリルがついたあまめソックス', emoji: '🩰', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'f3_loose', label: 'くしゅくしゅルーズソックス・カラーソックス', emoji: '✨', categoryWeights: { 'トレンド＆アイドル': 2, 'サブカル＆Y2K': 2 } },
      { id: 'f3_simple', label: '無地で履き心地ばつぐんなオーガニックソックス', emoji: '🌱', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'f4',
    genre: 'fashion',
    questionText: '寒い日に羽織るなら、どのアウターが好き？',
    description: '秋冬や春先に大活躍のアウター！',
    options: [
      { id: 'f4_wind', label: '軽くて動きやすいマウンテンパーカー・ウインドブレーカー', emoji: '🧥', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f4_boa', label: 'もこもこあったかボアブルゾン・エコファー', emoji: '🧸', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'f4_duffle', label: '上品なチェック柄ジャケットやダッフルコート', emoji: '🍂', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'f4_cardigan', label: 'ふわっと優しいパステルカラーのカーディガン', emoji: '🌸', categoryWeights: { 'スウィート＆ガーリー': 2, 'ナチュラル＆ピュア': 2 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'f5',
    genre: 'fashion',
    questionText: 'お気に入りのスニーカーの色は？',
    description: '下駄箱でもパッと目立つ靴はどれ？',
    options: [
      { id: 'f5_vivid', label: 'イエローやオレンジなど元気なビタミンカラー', emoji: '👟', colorCode: '#FBBF24', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f5_pastel', label: 'ピンクやラベンダーの優しいパステル', emoji: '🩰', colorCode: '#F472B6', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'f5_black', label: '黒×ホワイトのスタイリッシュなハイテク', emoji: '🖤', colorCode: '#0F172A', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'f5_beige', label: 'ベージュやブラウンのアースカラー', emoji: '🤎', colorCode: '#D97706', categoryWeights: { 'ナチュラル＆ピュア': 3, 'クラシック＆レトロ': 1 } },
      { id: 'f5_aurora', label: 'ホログラムやオーロラに輝くデザイン', emoji: '🌌', colorCode: '#C084FC', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
    ],
  },
  {
    id: 'f6',
    genre: 'fashion',
    questionText: 'お出かけバッグに選ぶならどれ？',
    description: '両手が空くタイプ？それともおしゃれ重視？',
    options: [
      { id: 'f6_body', label: 'ボディバッグ・サコッシュでアクティブに！', emoji: '🎒', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f6_heart', label: 'ハートやリボンのミニショルダーバッグ', emoji: '👜', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'f6_canvas', label: 'ナチュラルなキャンバス地トートバッグ', emoji: '🛍️', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'f6_clear', label: 'クリア素材やホログラムのY2Kポーチ', emoji: '📱', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
    ],
  },
  {
    id: 'f7',
    genre: 'fashion',
    questionText: 'コーディネートで一番大事にしたいポイントは？',
    description: '服を選ぶときのあなたのこだわり！',
    options: [
      { id: 'f7_move', label: '体育や休み時間も思いっきり走れる動きやすさ！', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f7_cute', label: '誰が見ても「かわいい！」ってキュンとする甘さ', emoji: '💖', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'f7_cool', label: '大人っぽくて周りと一味違うスマートさ', emoji: '🕶️', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'f7_comfy', label: 'リラックスできて自分らしくいられる心地よさ', emoji: '🍃', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'f7_trend', label: '雑誌やSNSで流行ってる最新のオシャレ感！', emoji: '🌟', categoryWeights: { 'トレンド＆アイドル': 3 } },
    ],
  },
  {
    id: 'f8',
    genre: 'fashion',
    questionText: '柄物のアイテムなら、どれがいちばん好き？',
    description: '服や文房具によく選ぶパターンは？',
    options: [
      { id: 'f8_border', label: 'ボーダー（しましま）やストライプ', emoji: '🏁', categoryWeights: { 'スポーティ＆アクティブ': 2, 'クール＆ストリート': 2 } },
      { id: 'f8_check', label: '上品なタータンチェック・ギンガムチェック', emoji: '🇬🇧', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'f8_flower', label: '可憐な小花柄やボタニカルフラワー', emoji: '🌼', categoryWeights: { 'スウィート＆ガーリー': 2, 'シーズン＆ネイチャー': 2 } },
      { id: 'f8_animal', label: 'ヒョウ柄やゼブラなどのアニマル柄アクセント', emoji: '🐆', categoryWeights: { 'アニマル＆マスコット': 3, 'クール＆ストリート': 1 } },
      { id: 'f8_space', label: '星空・星座・ギャラクシー柄', emoji: '✨', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
    ],
  },
  {
    id: 'f9',
    genre: 'fashion',
    questionText: 'キャップや帽子をかぶるなら、どれが似合うと思う？',
    description: '日差し対策にもおしゃれにも大活躍！',
    options: [
      { id: 'f9_cap', label: 'ロゴ入りベースボールキャップ', emoji: '🧢', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f9_beret', label: '絵描きさん風の上品なベレー帽', emoji: '🎨', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'f9_knit', label: '猫耳付きニット帽やポンポン付きワッチ', emoji: '🐱', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'f9_bucket', label: 'ストリート感あるバケットハット', emoji: '👒', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'f9_tiara', label: 'キラキラティアラや魔法使いのとんがり帽子', emoji: '👑', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 'f10',
    genre: 'fashion',
    questionText: '雨の日のファッション、テンションを上げるなら？',
    description: '雨の日もごきげんに過ごしたい！',
    options: [
      { id: 'f10_colorful', label: 'パッと明るいビタミンカラーの傘と長靴', emoji: '☔', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f10_lace', label: 'フリル付き傘やレインボー柄のレインポンチョ', emoji: '🌈', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'f10_clear', label: 'オーロラに透けるビニール傘で近未来風！', emoji: '🔮', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'f10_chic', label: 'ネイビーやカーキの落ち着いたシックな傘', emoji: '🌂', categoryWeights: { 'ナチュラル＆ピュア': 2, 'クール＆ストリート': 2 } },
    ],
  },
  {
    id: 'f11',
    genre: 'fashion',
    questionText: '休日の特別なおめかしワンピースならどれ？',
    description: 'お誕生日や発表会、テーマパークに着ていくなら？',
    options: [
      { id: 'f11_shirt', label: 'すっきり爽やかなシャツワンピース', emoji: '👗', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'f11_chiffon', label: 'レースやチュールたっぷりのプリンセスドレス', emoji: '👸', categoryWeights: { 'スウィート＆ガーリー': 3, 'ファンタジー＆ドリーム': 1 }, secretTag: 'magical' },
      { id: 'f11_camisole', label: 'Tシャツと重ね着するキャミワンピ', emoji: '✨', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'f11_retro', label: '大きめ丸襟が可愛いレトロクラシカルワンピ', emoji: '🕰️', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'f12',
    genre: 'fashion',
    questionText: '学校の体操服やジャージの着こなしは？',
    description: '体育の時間のあなたスタイル！',
    options: [
      { id: 'f12_active', label: '裾をしっかりイン！腕まくりして全力ダッシュ体制', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f12_cute', label: '可愛いヘアゴムで髪をキュッとまとめて差をつける', emoji: '🎀', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'f12_smart', label: 'すっきり着こなしてスマートに準備完了', emoji: '👌', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'f12_relaxed', label: '無理せずマイペースに心地よく参加', emoji: '🌱', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'f13',
    genre: 'fashion',
    questionText: '好きなアクセサリーや小物はどれ？',
    description: '休日のお出かけにつけたいアイテム！',
    options: [
      { id: 'f13_wrist', label: 'スポーティなリストバンドや防水デジタル時計', emoji: '⌚', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f13_heart', label: 'ぷっくりハートやビーズのリング・ネックレス', emoji: '💍', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'f13_silver', label: 'シルバーのチェーンアクセやイヤーカフ風ピン', emoji: '⛓️', categoryWeights: { 'クール＆ストリート': 3, 'サブカル＆Y2K': 1 }, secretTag: 'cyber' },
      { id: 'f13_gold', label: 'アンティーク風の金古美チャームや懐中時計', emoji: '🗝️', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 'f14',
    genre: 'fashion',
    questionText: 'デニムジャケット（Gジャン）を着るならどんな形？',
    description: '春・秋にぴったりの定番アイテム！',
    options: [
      { id: 'f14_over', label: 'ダボっと羽織れるビッグシルエット・オーバーサイズ', emoji: '🧥', categoryWeights: { 'クール＆ストリート': 3, 'トレンド＆アイドル': 1 } },
      { id: 'f14_cropped', label: '短め丈で脚長に見えるクロップド丈', emoji: '✨', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'f14_standard', label: 'ベーシックで長く着られる定番レギュラー丈', emoji: '👖', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'f14_frill', label: '襟元や裾にフリル・刺繍がついたガーリーデザイン', emoji: '🌸', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
  {
    id: 'f15',
    genre: 'fashion',
    questionText: 'パジャマ・部屋着はどんなタイプが好き？',
    description: 'おうち時間や修学旅行・お泊まり会で着たいもの！',
    options: [
      { id: 'f15_tshirt', label: '着心地最高のTシャツ＆ハーフパンツスウェット', emoji: '👕', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f15_animal', label: 'モコモコうさぎやくまの着ぐるみパジャマ', emoji: '🐰', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'f15_satin', label: 'さらさらサテン生地やレース付きパジャマセット', emoji: '🌙', categoryWeights: { 'スウィート＆ガーリー': 2, 'トレンド＆アイドル': 2 } },
      { id: 'f15_cotton', label: '吸水性ばつぐんの綿100%ダブルガーゼパジャマ', emoji: '☁️', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'f16',
    genre: 'fashion',
    questionText: '夏に着たい水着のタイプは？',
    description: 'プールや海水浴、夏の思い出に！',
    options: [
      { id: 'f16_rash', label: 'ラッシュガードつきスポーティセパレート', emoji: '🏄‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f16_frill', label: 'オフショルやフリル付きのかわいいビキニ/ワンピ', emoji: '👙', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'f16_mermaid', label: 'エメラルドやパープルのマーメイド風デザイン', emoji: '🧜‍♀️', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
      { id: 'f16_chic', label: 'シンプルブラックやカーキの大人っぽスイムウェア', emoji: '🩱', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
  {
    id: 'f17',
    genre: 'fashion',
    questionText: 'マフラーや手袋の冬小物は？',
    description: '寒い通学路をポカポカにする冬の相棒！',
    options: [
      { id: 'f17_neck', label: 'すっぽり被れるネックウォーマー＆スマホ対応手袋', emoji: '🧤', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f17_check', label: '大判チェック柄マフラーをぐるぐる巻き！', emoji: '🧣', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'f17_paws', label: '肉球付きミトンやもこもこイヤーマフ', emoji: '🐾', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'f17_white', label: '純白のふわふわファーティペット', emoji: '❄️', categoryWeights: { 'スウィート＆ガーリー': 3, 'シーズン＆ネイチャー': 1 } },
    ],
  },
  {
    id: 'f18',
    genre: 'fashion',
    questionText: 'もし自分のブランドを作るなら、どんなテーマにする？',
    description: 'あなたがデザイナーになったとしたら！',
    options: [
      { id: 'f18_energy', label: '世界中の子どもたちを元気にするアクティブウェア', emoji: '⚡', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f18_magic', label: '魔法少女に変身できるドリーミーコレクション', emoji: '🪄', categoryWeights: { 'ファンタジー＆ドリーム': 3, 'スウィート＆ガーリー': 1 }, secretTag: 'magical' },
      { id: 'f18_future', label: '光る未来都市のサイバーパンクファッション', emoji: '🏙️', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'f18_earth', label: '地球にやさしい自然素材のエシカルブランド', emoji: '🌍', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'f19',
    genre: 'fashion',
    questionText: '移動ポケット（マルチポケット）を付けるなら？',
    description: 'ハンカチ＆ティッシュを入れる必須アイテム！',
    options: [
      { id: 'f19_mesh', label: 'メッシュ素材でスポーティなロゴテープつき', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f19_lace', label: 'チュールレースやリボンたっぷりのプリンセス仕様', emoji: '🎀', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'f19_cute', label: '好きなキャラクターや柴犬・猫のフェイス型', emoji: '🐶', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 'f19_chic', label: '洋服になじむシンプルな無地スエード・レザー調', emoji: '🎒', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
    ],
  },
  {
    id: 'f20',
    genre: 'fashion',
    questionText: '鏡を見たとき、どんな自分に出会えたら一番嬉しい？',
    description: '服を着替えた後の最高の瞬間！',
    options: [
      { id: 'f20_smile', label: '太陽みたいに笑顔がはじける元気な自分！', emoji: '😆', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'f20_lovely', label: 'お姫さまみたいに愛らしくてキュートな自分！', emoji: '🥰', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'f20_cool', label: '堂々としてて芯があるかっこいい自分！', emoji: '😎', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'f20_free', label: '自然体でのびのび飾らない自分！', emoji: '🍃', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'f20_shine', label: '誰も見たことがない特別な輝きを放つ自分！', emoji: '✨', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
    ],
  },
];
