import { PoolQuestion } from './types';

export const FOOD_QUESTIONS: PoolQuestion[] = [
  {
    id: 'fo1',
    genre: 'food',
    questionText: '休日の贅沢ランチに選ぶならどれ？',
    description: 'お腹ペコペコ！何を食べに行こう？',
    options: [
      { id: 'fo1_burger', label: 'ジューシーハンバーグ＆山盛りフライドポテト', emoji: '🍔', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo1_pancake', label: '生クリームたっぷりふわふわスフレパンケーキ', emoji: '🥞', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'fo1_pizza', label: 'チーズがびよーんと伸びる焼きたてピザ', emoji: '🍕', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'fo1_omurice', label: '洋食屋さんのふわとろ卵オムライス', emoji: '🍳', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'fo2',
    genre: 'food',
    questionText: 'カフェやコンビニで頼むドリンクはどれが好き？',
    description: '喉をうるおすお気に入りドリンク！',
    options: [
      { id: 'fo2_tapioca', label: 'もちもち大粒タピオカミルクティー', emoji: '🧋', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'fo2_float', label: 'メロンソーダにバニラアイスが乗ったクリームソーダ', emoji: '🍈', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'fo2_smoothie', label: 'フルーツとヨーグルトの爽快スムージー', emoji: '🥤', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo2_tea', label: 'ほっと一息つけるハーブティーやほうじ茶ラテ', emoji: '🍵', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'fo2_aurora', label: '青から紫に色が変わるバタフライピーマジックティー', emoji: '🔮', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cyber' },
    ],
  },
  {
    id: 'fo3',
    genre: 'food',
    questionText: 'ケーキ屋さんでショーケースを見たとき、一番惹かれるのは？',
    description: '宝石みたいに並ぶスイーツたち！',
    options: [
      { id: 'fo3_short', label: '真っ赤ないちごが乗った王道の苺ショートケーキ', emoji: '🍰', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'fo3_choco', label: 'ビターで濃厚なガトーショコラ・ザッハトルテ', emoji: '🍫', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
      { id: 'fo3_tart', label: '季節のフルーツがぎっしり敷き詰められたフルーツタルト', emoji: '🍇', categoryWeights: { 'シーズン＆ネイチャー': 3 } },
      { id: 'fo3_montblanc', label: '栗の香りとクリームが贅沢なモンブラン', emoji: '🌰', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'fo4',
    genre: 'food',
    questionText: '夏祭りの屋台で絶対に食べたいかき氷の味は？',
    description: 'キーンと冷たい夏の風物詩！',
    options: [
      { id: 'fo4_blue', label: '舌が青くなっちゃうブルーハワイ！', emoji: '🍧', categoryWeights: { 'クール＆ストリート': 2, 'スポーティ＆アクティブ': 2 } },
      { id: 'fo4_strawberry', label: '練乳たっぷりいちごミルク味！', emoji: '🍓', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'fo4_matcha', label: 'あずきと白玉がのった宇治金時抹茶味！', emoji: '🍵', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'fo4_rainbow', label: '全シロップをかけたレインボーかき氷！', emoji: '🌈', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'fo5',
    genre: 'food',
    questionText: '朝ごはんに出てきたら一番嬉しいものは？',
    description: '今日も1日元気にスタート！',
    options: [
      { id: 'fo5_toast', label: 'バターがじゅわっと染みた厚切りトースト＆目玉焼き', emoji: '🍞', categoryWeights: { 'クラシック＆レトロ': 2, 'ナチュラル＆ピュア': 2 } },
      { id: 'fo5_onigiri', label: '鮭やツナマヨのおにぎり＆あったかいお味噌汁', emoji: '🍙', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'fo5_cereal', label: 'フルーツグラノーラやチョコシリアル＆ミルク', emoji: '🥣', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo5_french', label: 'メープルシロップたっぷりのフレンチトースト', emoji: '🍯', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
  {
    id: 'fo6',
    genre: 'food',
    questionText: 'クレープ屋さんで注文するならどれ？',
    description: '焼きたて生地に具材をくるっと巻いて！',
    options: [
      { id: 'fo6_banana', label: 'バナナチョコ生クリーム（不動の王道！）', emoji: '🍌', categoryWeights: { 'トレンド＆アイドル': 2, 'スウィート＆ガーリー': 2 } },
      { id: 'fo6_berry', label: 'いちごミルフィーユ＆カスタード', emoji: '🍓', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'fo6_snack', label: 'ツナマヨレタスやハムチーズのおかず系クレープ！', emoji: '🥗', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo6_butter', label: 'エシレバターとシュガーだけのシンプルな大人味', emoji: '🧈', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'fo7',
    genre: 'food',
    questionText: '駄菓子屋さんで300円あったら何を買う？',
    description: 'カゴを持って真剣に計算する時間！',
    options: [
      { id: 'fo7_umaibo', label: 'うまい棒をいろんな味でまとめ買い！', emoji: '🥢', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo7_gummy', label: 'なが〜いグミやパチパチはじけるキャンディ！', emoji: '🍬', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'fo7_choco', label: '占い付きのチョコや可愛いラムネ瓶', emoji: '🍫', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'fo7_katsu', label: 'ビッグカツやすもも漬けなど渋くて美味しい定番！', emoji: '🍘', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'fo8',
    genre: 'food',
    questionText: 'アイスクリームのフレーバーで一番好きなのは？',
    description: 'コーンにする？カップにする？',
    options: [
      { id: 'fo8_mint', label: '爽やかで映えるチョコミント！', emoji: '🌱', categoryWeights: { 'クール＆ストリート': 2, 'トレンド＆アイドル': 2 } },
      { id: 'fo8_vanilla', label: 'リッチで濃厚なバニラビーンズ入りバニラ', emoji: '🍨', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'fo8_cotton', label: 'パステルカラーのコットンキャンディ・ポッピングシャワー', emoji: '🎪', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
      { id: 'fo8_fruit', label: '果汁たっぷりのマンゴーやブラッドオレンジシャーベット', emoji: '🥭', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
    ],
  },
  {
    id: 'fo9',
    genre: 'food',
    questionText: '遠足や運動会のお弁当に入っていたら一番嬉しいおかずは？',
    description: 'お母さん・お父さんの愛情が詰まったお弁当箱！',
    options: [
      { id: 'fo9_karaage', label: 'サクサクでジューシーな鶏のから揚げ！', emoji: '🍗', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo9_tamago', label: 'ちょっぴり甘い黄色い卵焼き＆タコさんウインナー', emoji: '🐙', categoryWeights: { 'アニマル＆マスコット': 2, 'スウィート＆ガーリー': 2 } },
      { id: 'fo9_sand', label: 'ハム・チーズ・いちごジャムのカラフルサンドイッチ', emoji: '🥪', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'fo9_onigiri', label: '可愛い海苔アートがついたデコおにぎり！', emoji: '🍙', categoryWeights: { 'アニマル＆マスコット': 3 } },
    ],
  },
  {
    id: 'fo10',
    genre: 'food',
    questionText: '果物（フルーツ）の中で一番大すきなのは？',
    description: 'みずみずしくて甘い自然の恵み！',
    options: [
      { id: 'fo10_strawberry', label: '甘酸っぱくて可愛い真っ赤ないちご！', emoji: '🍓', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'fo10_muscat', label: '皮ごとプチッと弾けるシャインマスカット！', emoji: '🍇', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'fo10_orange', label: '太陽の光を浴びたジューシーなみかんやオレンジ！', emoji: '🍊', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo10_peach', label: 'とろけるように甘い白桃・ピンクピーチ！', emoji: '🍑', categoryWeights: { 'ファンタジー＆ドリーム': 2, 'ナチュラル＆ピュア': 2 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'fo11',
    genre: 'food',
    questionText: 'パン屋さんに入って最初にトングでつかむパンは？',
    description: '焼きたての香ばしい匂いが漂う店内！',
    options: [
      { id: 'fo11_melon', label: '外はサクサク中はふわふわの焼きたてメロンパン！', emoji: '🍈', categoryWeights: { 'スウィート＆ガーリー': 2, 'クラシック＆レトロ': 2 } },
      { id: 'fo11_croissant', label: 'バターの層が何層にも重なったサクサククロワッサン', emoji: '🥐', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'fo11_curry', label: '揚げたてアツアツのカレーパンやウインナーロール', emoji: '🌭', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo11_choco', label: '可愛い動物の形をしたチョコクリームパン！', emoji: '🐼', categoryWeights: { 'アニマル＆マスコット': 3 } },
    ],
  },
  {
    id: 'fo12',
    genre: 'food',
    questionText: '回転寿司に行ったら、何皿も食べちゃうお気に入りは？',
    description: 'レーンを流れてくるお皿にワクワク！',
    options: [
      { id: 'fo12_salmon', label: 'とろけるサーモン（炙りチーズサーモンも！）', emoji: '🍣', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'fo12_tuna', label: '王道の赤身マグロやネギトロ軍艦！', emoji: '🐟', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo12_tamago', label: 'あま〜い出汁巻き玉子やコーンマヨ軍艦！', emoji: '🌽', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'fo12_desert', label: 'お寿司のあとのパフェやプリン・ポテトフライ！', emoji: '🍟', categoryWeights: { 'サブカル＆Y2K': 2, 'スウィート＆ガーリー': 2 } },
    ],
  },
  {
    id: 'fo13',
    genre: 'food',
    questionText: '友達と一緒にお菓子作りをするなら何を作りたい？',
    description: 'エプロンをつけてパティシエ気分！',
    options: [
      { id: 'fo13_cookie', label: 'アイシングでカラフルにお絵かきする型抜きクッキー', emoji: '🍪', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'fo13_cupcake', label: 'クリームを絞ってトッピングする可愛いカップケーキ', emoji: '🧁', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'unicorn' },
      { id: 'fo13_choco', label: '生チョコトリュフやチョコバナナ！', emoji: '🍫', categoryWeights: { 'クール＆ストリート': 2 } },
      { id: 'fo13_waffle', label: 'ワッフルメーカーで焼くカリカリベルギーワッフル', emoji: '🧇', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 'fo14',
    genre: 'food',
    questionText: '寒い冬の日にフーフーしながら食べたいあったかごはんは？',
    description: '湯気が立ち上るごちそう！',
    options: [
      { id: 'fo14_nabe', label: '家族やお友達と囲むあったかお鍋やうどん！', emoji: '🍲', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'fo14_gratin', label: 'こんがり焦げ目のついたエビとマカロニの熱々グラタン', emoji: '🧀', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'fo14_soup', label: 'かぼちゃやコーンの濃厚ポタージュスープ', emoji: '🥣', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'fo14_chuman', label: 'コンビニの肉まんやピザまん！', emoji: '🥟', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
    ],
  },
  {
    id: 'fo15',
    genre: 'food',
    questionText: '映画館に行ったら食べるスナックはどれ？',
    description: '暗闇の中でつまむお供！',
    options: [
      { id: 'fo15_caramel', label: '甘くて香ばしいキャラメルポップコーン！', emoji: '🍿', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'fo15_salt', label: 'シンプルイズベストな塩バターポップコーン！', emoji: '🧈', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'fo15_churros', label: 'サクサクシナモンやチョコのロングチュロス！', emoji: '🥖', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'fo15_nachos', label: 'サルサソースととろけるチーズのナチョス！', emoji: '🧀', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
];
