import { PoolQuestion } from './types';

export const MOOD_QUESTIONS: PoolQuestion[] = [
  {
    id: 'm1',
    genre: 'mood',
    questionText: '直感で「これ！」と思う大すきな色はどれ？',
    description: 'あなたのオーラを輝かせるメインカラー！',
    options: [
      { id: 'm1_yellow', label: 'あかるい黄色・ビタミンオレンジ', emoji: '☀️', colorCode: '#FBBF24', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm1_pink', label: 'スウィートピンク・パステルローズ', emoji: '🌸', colorCode: '#F472B6', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'm1_blue', label: 'さわやかアクアブルー・深海ネイビー', emoji: '🌊', colorCode: '#38BDF8', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'm1_green', label: 'やさしい若草グリーン・オリーブベージュ', emoji: '🍀', colorCode: '#84CC16', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'm1_purple', label: 'きらきらラベンダーパープル・オーロラ', emoji: '✨', colorCode: '#C084FC', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
      { id: 'm1_rainbow', label: '奇跡のレインボーパステル！', emoji: '🌈', colorCode: '#F472B6', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
      { id: 'm1_silver', label: 'サイバーシルバー・ネオングレイ', emoji: '⚡', colorCode: '#94A3B8', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'm1_gold', label: '古代の黄金ゴールド・ロイヤルアンバー', emoji: '👑', colorCode: '#F59E0B', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 'm2',
    genre: 'mood',
    questionText: '今日のあなたの気分はどんな感じ？',
    description: '心のコンパスが指している方向は？',
    options: [
      { id: 'm2_energetic', label: '元気ハッピー！走り回りたいエネルギー満タン気分！', emoji: '⚡', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm2_dreamy', label: 'ふわふわ夢心地・お姫さま気分で過ごしたい！', emoji: '🎀', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 'm2_cool', label: '落ち着いてスマートにかっこよくキメたい！', emoji: '🕶️', categoryWeights: { 'クール＆ストリート': 3 }, secretTag: 'cyber' },
      { id: 'm2_relax', label: 'のんびりリラックス・やさしい気持ちで癒やされたい', emoji: '🌿', categoryWeights: { 'ナチュラル＆ピュア': 3 }, secretTag: 'pharaoh' },
      { id: 'm2_sparkle', label: 'キラキラ注目の的！ドキドキワクワク冒険したい！', emoji: '🌟', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
    ],
  },
  {
    id: 'm3',
    genre: 'mood',
    questionText: 'もし一つだけ超能力が手に入るなら、どれを選ぶ？',
    description: '夢にまで見たスーパーパワー！',
    options: [
      { id: 'm3_speed', label: '新幹線よりも速く走れるスピード！', emoji: '💨', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm3_transform', label: 'きらめくステッキで何にでも変身できる魔法！', emoji: '🪄', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'magical' },
      { id: 'm3_teleport', label: '電脳空間や好きな場所に一瞬でテレポート！', emoji: '🌐', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'm3_talk_animal', label: '世界中の動物や植物とおしゃべりできる能力！', emoji: '🐾', categoryWeights: { 'アニマル＆マスコット': 3, 'シーズン＆ネイチャー': 2 } },
      { id: 'm3_time', label: '時を操り、古代や未来を自由に行き来できる力！', emoji: '⏳', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 'm4',
    genre: 'mood',
    questionText: '夜空を見上げたとき、一番見たい景色は？',
    description: '満天の星が瞬く大宇宙！',
    options: [
      { id: 'm4_shooting', label: '願い事が叶うキラッと光る流れ星！', emoji: '🌠', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'm4_moon', label: '神秘的な光を放つ金色の満月や三日月', emoji: '🌙', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
      { id: 'm4_galaxy', label: '無数の星々が渦巻く銀河・天の川とオーロラ！', emoji: '🌌', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
      { id: 'm4_constellation', label: 'ペガスス座や白鳥座など神話の星座たち', emoji: '✨', categoryWeights: { 'シーズン＆ネイチャー': 3 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'm5',
    genre: 'mood',
    questionText: 'あなたが一番「自分らしいな」と感じる瞬間は？',
    description: '心が一番ピカピカ輝くとき！',
    options: [
      { id: 'm5_sports', label: '夢中になって走ったりボールを追いかけているとき', emoji: '⚽', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm5_fashion', label: 'お気に入りの服を着て鏡の前でポーズをとったとき', emoji: '👗', categoryWeights: { 'トレンド＆アイドル': 3, 'スウィート＆ガーリー': 2 } },
      { id: 'm5_create', label: '絵や工作・料理など自分の世界を創っているとき', emoji: '🎨', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'm5_friend', label: '友達と大笑いして「楽しい！」って叫んでいるとき', emoji: '😆', categoryWeights: { 'スポーティ＆アクティブ': 2, 'トレンド＆アイドル': 2 } },
      { id: 'm5_nature', label: 'そよ風を感じて日なたぼっこしているとき', emoji: '🍃', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'm6',
    genre: 'mood',
    questionText: '誕生日のプレゼントに頼みたいものは？',
    description: '1年に1度の特別な願い事！',
    options: [
      { id: 'm6_roller', label: 'キックボードやスケートボード・スポーツギア！', emoji: '🛹', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm6_jewel', label: '宝石箱や可愛いメイクボックス・おめかしセット！', emoji: '💎', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'm6_game', label: '最新ゲームのソフトやデジタルガジェット！', emoji: '🎮', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 'm6_camera', label: 'お気に入りの風景を撮れるトイカメラやチェキ！', emoji: '📷', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'm6_stuffed', label: '抱き枕サイズの超巨大なぬいぐるみ！', emoji: '🧸', categoryWeights: { 'アニマル＆マスコット': 3 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'm7',
    genre: 'mood',
    questionText: 'お守りとして持ち歩くなら、どの天然石・ジュエル？',
    description: 'あなたを守ってくれるパワーストーン！',
    options: [
      { id: 'm7_sun', label: '太陽の力を宿すシトリンやアンバー（琥珀）', emoji: '☀️', colorCode: '#FBBF24', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm7_rose', label: '愛と優しさを呼ぶローズクォーツ（ピンク水晶）', emoji: '💖', colorCode: '#F472B6', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'm7_lapis', label: '古代ファラオが愛した深青のラピスラズリ', emoji: '👑', colorCode: '#1E40AF', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
      { id: 'm7_amethyst', label: '直感を研ぎ澄ます紫のアメジストやオパール', emoji: '🔮', colorCode: '#C084FC', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
      { id: 'm7_diamond', label: '虹色に光を反射する純白のクリスタルダイヤ', emoji: '💎', colorCode: '#F8FAFC', categoryWeights: { 'トレンド＆アイドル': 2 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 'm8',
    genre: 'mood',
    questionText: 'お友達から「〇〇ちゃんってどんな人？」と聞かれたら？',
    description: 'まわりから見たあなたの素敵な魅力！',
    options: [
      { id: 'm8_cheerful', label: '「いつも明るくて元気で、クラスの太陽！」', emoji: '☀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm8_cute', label: '「優しくて可愛くて、お花やスイーツが似合う！」', emoji: '🌸', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'm8_cool', label: '「自分のこだわりがあって、頼れるかっこいい人！」', emoji: '😎', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'm8_calm', label: '「一緒にいるとホッとする、思いやりのある癒やし系！」', emoji: '🍵', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 'm8_unique', label: '「個性的でセンスが良くて、いつも面白いこと知ってる！」', emoji: '✨', categoryWeights: { 'トレンド＆アイドル': 2, 'サブカル＆Y2K': 2 } },
    ],
  },
  {
    id: 'm9',
    genre: 'mood',
    questionText: '絵本や冒険物語の主人公になるなら、どんな役？',
    description: '物語のページを開いて冒険へ！',
    options: [
      { id: 'm9_knight', label: '仲間を守るために剣を振るう勇敢な騎士！', emoji: '⚔️', categoryWeights: { 'スポーティ＆アクティブ': 2, 'ファンタジー＆ドリーム': 2 } },
      { id: 'm9_princess', label: 'みんなから愛される心優しいプリンセス！', emoji: '👸', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 'm9_alchemist', label: '星の砂や薬草を調合するミステリアスな錬金術師', emoji: '🧪', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cyber' },
      { id: 'm9_empress', label: '王国を繁栄に導く聡明で気高い黄金の女王', emoji: '👑', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
      { id: 'm9_explorer', label: '地図にない未開の島を探検する大冒険家！', emoji: '🧭', categoryWeights: { 'シーズン＆ネイチャー': 3 } },
    ],
  },
  {
    id: 'm10',
    genre: 'mood',
    questionText: '今日このあとの時間、どんな風に過ごせたら最高？',
    description: '診断が終わったあとの楽しみ！',
    options: [
      { id: 'm10_jump', label: '新しいヘアアレンジに挑戦して鏡の前でニコッ！', emoji: '💁‍♀️', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 'm10_share', label: 'お友達やお母さんに結果を見せておしゃべり！', emoji: '🗣️', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'm10_go', label: 'お気に入りの服を着てお出かけにダッシュ！', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'm10_secret', label: 'シークレットスタイルの出現ヒントを解き明かす！', emoji: '🕵️‍♀️', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
    ],
  },
];
