import { PoolQuestion } from './types';

export const SCHOOL_QUESTIONS: PoolQuestion[] = [
  {
    id: 's1',
    genre: 'school',
    questionText: '学校の休み時間、何をして過ごすのが一番すき？',
    description: 'チャイムが鳴ったあとの楽しい時間！',
    options: [
      { id: 's1_tag', label: '校庭でドッジボール・鬼ごっこ・うんてい！', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's1_talk', label: '教室でお友達とおしゃべりやお手紙交換', emoji: '💌', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 's1_draw', label: '自由帳にイラストを描いたり漫画を読む', emoji: '✏️', categoryWeights: { 'サブカル＆Y2K': 2, 'ナチュラル＆ピュア': 1 } },
      { id: 's1_library', label: '図書室で静かに本を借りたり探検する', emoji: '📚', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 's2',
    genre: 'school',
    questionText: '給食で出たら一番テンションが上がるメニューは？',
    description: 'お昼の時間が待ちきれない大好物！',
    options: [
      { id: 's2_bread', label: '揚げパン（きなこ・ココア）＆フルーツポンチ', emoji: '🥖', categoryWeights: { 'スウィート＆ガーリー': 2, 'クラシック＆レトロ': 2 } },
      { id: 's2_curry', label: '定番のポークカレーライス＆ツナサラダ', emoji: '🍛', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's2_ramen', label: 'あったか味噌ラーメンやワンタンスープ', emoji: '🍜', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 's2_dessert', label: '特別な日のアイスクリームやクレープ！', emoji: '🍨', categoryWeights: { 'トレンド＆アイドル': 2 }, secretTag: 'unicorn' },
    ],
  },
  {
    id: 's3',
    genre: 'school',
    questionText: 'ペンケース（筆箱）はどんな形・色を使ってる？',
    description: '毎日机の上にある相棒！',
    options: [
      { id: 's3_mesh', label: '中身が見えるメッシュ・クリアポーチ型', emoji: '🔍', categoryWeights: { 'トレンド＆アイドル': 2, 'サブカル＆Y2K': 2 } },
      { id: 's3_animal', label: 'ぬいぐるみみたいにふわふわな動物ペンポーチ', emoji: '🧸', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 's3_box', label: '両面開きの多機能マグネット筆箱', emoji: '📐', categoryWeights: { 'スポーティ＆アクティブ': 2 } },
      { id: 's3_leather', label: 'シックでシンプルなスタンド型ペンケース', emoji: '🖋️', categoryWeights: { 'クラシック＆レトロ': 3 } },
    ],
  },
  {
    id: 's4',
    genre: 'school',
    questionText: '好きな教科・授業はどれ？',
    description: '時間割を見て嬉しくなる科目は？',
    options: [
      { id: 's4_pe', label: '体育！走ったり球技したり体を動かすこと！', emoji: '⚽', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's4_art', label: '図工！絵を描いたり粘土や木で作品を作ること！', emoji: '🎨', categoryWeights: { 'スウィート＆ガーリー': 2, 'サブカル＆Y2K': 2 } },
      { id: 's4_music', label: '音楽！歌ったりリコーダーや鍵盤ハーモニカを弾くこと！', emoji: '🎵', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
      { id: 's4_science', label: '理科！実験や生き物の観察、星空の観察！', emoji: '🔬', categoryWeights: { 'シーズン＆ネイチャー': 3 }, secretTag: 'cyber' },
      { id: 's4_history', label: '社会・歴史！昔の暮らしや世界の物語を知ること！', emoji: '🏛️', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 's5',
    genre: 'school',
    questionText: '運動会・体育祭で一番好きな種目は？',
    description: 'みんなで赤組白組で応援合戦！',
    options: [
      { id: 's5_relay', label: 'クラス対抗全員リレー・徒競走！', emoji: '🏃‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's5_dance', label: '学年の表現ダンス・フラッグ・よさこい！', emoji: '💃', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
      { id: 's5_tama', label: '玉入れや大玉転がし・綱引き', emoji: '🔴', categoryWeights: { 'ナチュラル＆ピュア': 2 } },
      { id: 's5_cheer', label: '応援団でメガホンを持って声を出すこと！', emoji: '📣', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
  {
    id: 's6',
    genre: 'school',
    questionText: '連絡帳や自由帳の表紙をデコるなら？',
    description: '自分だけのオリジナルノートに！',
    options: [
      { id: 's6_sticker', label: 'ぷくぷくシールやラインストーンでキラキラに！', emoji: '✨', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 's6_masking', label: 'おしゃれなマスキングテープでストライプやチェック！', emoji: '🏷️', categoryWeights: { 'クラシック＆レトロ': 2, 'ナチュラル＆ピュア': 2 } },
      { id: 's6_illust', label: '自分でかわいいキャラクターやロゴを直筆！', emoji: '🖊️', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 's6_clean', label: '何も貼らずにシンプル＆綺麗に使う！', emoji: '📄', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
  {
    id: 's7',
    genre: 'school',
    questionText: '学校に持っていく水筒（マイボトル）のデザインは？',
    description: '水分補給に毎日欠かせない水筒！',
    options: [
      { id: 's7_sport', label: '直飲みできる大容量のスポーツ保冷ボトル', emoji: '💧', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's7_pastel', label: 'グラデーションやパステルカラーの可愛いスリムボトル', emoji: '🌸', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 's7_matte', label: 'マットなブラックやステンレスシルバーのボトル', emoji: '🖤', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 's7_animal', label: 'くまさんやうさぎのイラスト入りボトルカバー付き', emoji: '🐰', categoryWeights: { 'アニマル＆マスコット': 3 } },
    ],
  },
  {
    id: 's8',
    genre: 'school',
    questionText: '席替えで一番座りたい場所はどこ？',
    description: 'ドキドキワクワクの席替えタイム！',
    options: [
      { id: 's8_window', label: '窓際の一番後ろ！外の景色や空を眺められる特等席', emoji: '🪟', categoryWeights: { 'ファンタジー＆ドリーム': 2, 'シーズン＆ネイチャー': 2 } },
      { id: 's8_center', label: 'クラスのど真ん中！みんなとワイワイ話せる場所', emoji: '🙋‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 2, 'トレンド＆アイドル': 2 } },
      { id: 's8_front', label: '黒板がよく見える一番前！授業に集中できる席', emoji: '📖', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 's8_hall', label: '廊下側の後ろ！休み時間になったら即ダッシュできる席', emoji: '💨', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
    ],
  },
  {
    id: 's9',
    genre: 'school',
    questionText: '係活動・委員会を選ぶならどれ？',
    description: 'みんなのために活躍するお仕事！',
    options: [
      { id: 's9_pe', label: '体育委員・レク係！ボールの管理やお楽しみ会を企画！', emoji: '⚽', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's9_broadcast', label: '放送委員会・音楽係！お昼の音楽やアナウンスを担当！', emoji: '🎙️', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 's9_env', label: '美化・飼育・園芸委員！お花の水やりやウサギのお世話！', emoji: '🌻', categoryWeights: { 'アニマル＆マスコット': 2, 'シーズン＆ネイチャー': 2 } },
      { id: 's9_book', label: '図書委員会！新刊の紹介ポスターや本の整理！', emoji: '📚', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 's10',
    genre: 'school',
    questionText: '遠足や校外学習のしおりをもらったら、最初に何を見る？',
    description: '行く前から待ちきれない行事！',
    options: [
      { id: 's10_snack', label: '「おやつの金額ルール（300円まで等）」とお弁当の時間！', emoji: '🍫', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 's10_place', label: 'アスレチックや広場など遊ぶ場所・ルートの地図！', emoji: '🗺️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's10_souvenir', label: 'お土産屋さんで買える記念品やキーホルダー！', emoji: '🛍️', categoryWeights: { 'アニマル＆マスコット': 2, 'トレンド＆アイドル': 2 } },
      { id: 's10_history', label: '見学する施設や博物館の見どころ解説！', emoji: '🏛️', categoryWeights: { 'クラシック＆レトロ': 3 }, secretTag: 'pharaoh' },
    ],
  },
  {
    id: 's11',
    genre: 'school',
    questionText: 'お友達とお揃い（ニコイチ）にするなら何がいい？',
    description: '親友と一緒にお揃いを楽しみたい！',
    options: [
      { id: 's11_key', label: 'ランドセルにつけるハートが合体するペアキーホルダー', emoji: '🗝️', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 's11_scrunchie', label: '色違いのおしゃれなヘアゴムやシュシュ', emoji: '🎀', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 's11_tshirt', label: '休日に合わせる色違いのロゴTシャツ・スニーカー', emoji: '👟', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's11_pen', label: 'おそろいのキラキラペンやシール帳', emoji: '🖊️', categoryWeights: { 'サブカル＆Y2K': 3 } },
    ],
  },
  {
    id: 's12',
    genre: 'school',
    questionText: '下校のとき、お友達とどんな話で盛り上がる？',
    description: '帰り道の楽しいおしゃべりタイム！',
    options: [
      { id: 's12_tv', label: '昨日見た好きなアニメ・YouTube・ドラマの感想！', emoji: '📺', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 's12_play', label: '「このあと宿題終わったら公園で遊ぼ！」の作戦会議', emoji: '🛹', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's12_idol', label: '好きな推し・アイドル・音楽の新曲トーク！', emoji: '🎤', categoryWeights: { 'トレンド＆アイドル': 3 } },
      { id: 's12_secret', label: 'だれにも言えない秘密のガールズトーク・恋バナ！', emoji: '🤫', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
    ],
  },
  {
    id: 's13',
    genre: 'school',
    questionText: '彫刻刀や裁縫セットのデザイン、選ぶならどれ？',
    description: '高学年で注文するお気に入りの裁縫箱！',
    options: [
      { id: 's13_sport', label: 'スポーティなブランドロゴ入りメッシュバッグ', emoji: '⚡', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's13_ribbon', label: 'パステルパープルにオーロラリボンがついた可愛いデザイン', emoji: '💜', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'unicorn' },
      { id: 's13_cat', label: '可愛い黒猫や柴犬の刺繍が入ったアニマルデザイン', emoji: '🐱', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 's13_simple', label: 'シンプルブラックにゴールドファスナーの大人っぽスタイル', emoji: '🖤', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
  {
    id: 's14',
    genre: 'school',
    questionText: '学校の図書室で借りる本のジャンルは？',
    description: '雨の日や朝読書の時間に読む本！',
    options: [
      { id: 's14_magic', label: '魔法使いや魔女、妖精が登場するファンタジー小説', emoji: '🧙‍♀️', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'magical' },
      { id: 's14_detective', label: '名探偵が謎を解くミステリーや怖い話シリーズ', emoji: '🕵️‍♀️', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
      { id: 's14_animal', label: '動物の飼い方や図鑑、動物病院の感動ストーリー', emoji: '🐾', categoryWeights: { 'アニマル＆マスコット': 3 } },
      { id: 's14_fashion', label: '心理テスト・星座占い・ヘアアレンジのおしゃれ本', emoji: '💄', categoryWeights: { 'トレンド＆アイドル': 3 } },
    ],
  },
  {
    id: 's15',
    genre: 'school',
    questionText: '定規（ものさし）や消しゴムのこだわりは？',
    description: '筆箱に入っているステーショナリー！',
    options: [
      { id: 's15_scent', label: 'いちごやチョコのあま〜い香りがする消しゴム', emoji: '🍓', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 's15_smart', label: '折れにくいアルミ定規やよく消えるMONO消しゴム', emoji: '📏', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 's15_glitter', label: '水とラメが入って動くキラキラスケール定規', emoji: '✨', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'unicorn' },
      { id: 's15_knead', label: '色を混ぜて遊べるカラフルなねり消し！', emoji: '🎨', categoryWeights: { 'サブカル＆Y2K': 3 } },
    ],
  },
  {
    id: 's16',
    genre: 'school',
    questionText: '夏休みの自由研究・工作で作るなら何がいい？',
    description: '新学期に教室に飾る自慢の作品！',
    options: [
      { id: 's16_craft', label: 'UVレジンやビーズで作るキラキラアクセサリー', emoji: '💎', categoryWeights: { 'スウィート＆ガーリー': 3 }, secretTag: 'magical' },
      { id: 's16_robot', label: 'ダンボールやモーターで作るハイテクからくり工作', emoji: '🤖', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 's16_plant', label: '押し花を使ったしおりや植物の観察日記', emoji: '🌸', categoryWeights: { 'シーズン＆ネイチャー': 3 } },
      { id: 's16_space', label: '発光塗料で星座を再現したプラネタリウム模型', emoji: '🌌', categoryWeights: { 'ファンタジー＆ドリーム': 3 }, secretTag: 'cosmic' },
    ],
  },
  {
    id: 's17',
    genre: 'school',
    questionText: '掃除の時間、どこを担当するのが一番好き？',
    description: 'みんなで校舎をピカピカにする時間！',
    options: [
      { id: 's17_hall', label: '長い廊下のモップがけ・雑巾がけレース！', emoji: '🧹', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's17_blackboard', label: '黒板を黒板消しクリーナーで真っ白に戻す係！', emoji: '⬛', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
      { id: 's17_flower', label: '教室の花瓶の水替えや黒板のチョーク補充', emoji: '💐', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
      { id: 's17_music', label: '音楽室や特別教室の棚をきれいに整頓！', emoji: '🎹', categoryWeights: { 'スウィート＆ガーリー': 2 } },
    ],
  },
  {
    id: 's18',
    genre: 'school',
    questionText: '学校のプール開き！一番楽しみなことは？',
    description: '夏の太陽の下、水しぶきをあげて！',
    options: [
      { id: 's18_swim', label: 'クロールや平泳ぎで何メートル泳げるかタイムアタック！', emoji: '🏊‍♀️', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 's18_game', label: '水中宝探し（リング拾い）や波のプールごっこ！', emoji: '🪙', categoryWeights: { 'トレンド＆アイドル': 2, 'アニマル＆マスコット': 2 } },
      { id: 's18_shower', label: '地獄のシャワーをみんなでキャーキャー叫びながらくぐる瞬間！', emoji: '🚿', categoryWeights: { 'スポーティ＆アクティブ': 2 } },
      { id: 's18_float', label: 'ビート板に浮いて青空を眺めるリラックスタイム', emoji: '☁️', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 's19',
    genre: 'school',
    questionText: '朝の読書タイム、どんなスタイルで読む？',
    description: '授業前の静かで落ち着く時間！',
    options: [
      { id: 's19_focus', label: '世界観にどっぷり引き込まれて集中して読む！', emoji: '📖', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 's19_comic', label: 'マンガでわかる偉人伝や学習コミックで楽しく知識ゲット！', emoji: '💡', categoryWeights: { 'スポーティ＆アクティブ': 2 } },
      { id: 's19_friend', label: '隣のお友達と同じ本を読んであとで感想を語り合う！', emoji: '👭', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
  {
    id: 's20',
    genre: 'school',
    questionText: 'クラスでお楽しみ会やレクをするなら何がやりたい？',
    description: '学期末の思い出づくりイベント！',
    options: [
      { id: 's20_talent', label: 'ダンスや歌、特技を披露するステージショー！', emoji: '🎤', categoryWeights: { 'トレンド＆アイドル': 3 }, secretTag: 'magical' },
      { id: 's20_game', label: '教室を使った暗闇宝探しやクイズ大会！', emoji: '🎯', categoryWeights: { 'サブカル＆Y2K': 3 }, secretTag: 'cyber' },
      { id: 's20_drama', label: 'みんなで衣装を作って小さな劇や寸劇！', emoji: '🎭', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 's20_dodge', label: '体育館で先生も交えたガチのドッジボール大会！', emoji: '🏐', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
    ],
  },
];
