import { PoolQuestion } from './types';

export const SECRET_FATE_QUESTIONS: PoolQuestion[] = [
  {
    id: 'sf1',
    genre: 'secret_fate',
    questionText: 'もし魔法やタイムスリップで1日だけ変身できるなら、どんな姿になりたい？',
    description: 'あなたの心の中に眠る、もうひとりの特別な自分を選んでみて！',
    options: [
      { id: 'sf1_kimetsu', label: '市松模様の羽織をまとい、悪鬼を滅ぼす熱き剣士！', emoji: '⚔️', secretTag: 'kimetsu', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
      { id: 'sf1_unicorn', label: '虹色のオーラをまとい、空を翔けるユニコーンエンジェル！', emoji: '🦄', secretTag: 'unicorn', categoryWeights: { 'スウィート＆ガーリー': 2, 'ファンタジー＆ドリーム': 2 } },
      { id: 'sf1_girly', label: 'お砂糖菓子のお城で暮らす、究極のストロベリードール姫！', emoji: '🍓', secretTag: 'secret_girly', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf1_cyber', label: '西暦3000年の近未来を駆け抜ける、電脳ネオンサイバーエージェント！', emoji: '⚡', secretTag: 'cyber', categoryWeights: { 'サブカル＆Y2K': 2, 'クール＆ストリート': 2 } },
    ],
  },
  {
    id: 'sf2',
    genre: 'secret_fate',
    questionText: '宝箱から手に入れたい「伝説のシークレットアイテム」はどれ？',
    description: 'ひとつだけ手に入るとしたら、どれに一番ワクワクする？',
    options: [
      { id: 'sf2_kimetsu', label: '藤の花が優雅に香る蝶の羽織と、毒を調合する秘密の小瓶！', emoji: '🦋', secretTag: 'kimetsu', categoryWeights: { 'クラシック＆レトロ': 2, 'スウィート＆ガーリー': 1 } },
      { id: 'sf2_magical', label: '星屑の光で変身できる、キラキラな魔法のコンパクト＆ステッキ！', emoji: '🪄', secretTag: 'magical', categoryWeights: { 'スウィート＆ガーリー': 2, 'トレンド＆アイドル': 2 } },
      { id: 'sf2_pop', label: '原宿の街をジャックする、カラフルネオモンスターのリュック！', emoji: '👾', secretTag: 'secret_pop', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'sf2_natural', label: '古い森の奥深くで授かる、聖なるボタニカルハーブと月の花冠！', emoji: '🍃', secretTag: 'secret_natural', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'sf3',
    genre: 'secret_fate',
    questionText: '特別なお祭りで、周りをあっと言わせるスペシャル衣装を着るなら？',
    description: 'みんなの視線を独り占めしちゃう憧れのコスチュームは？',
    options: [
      { id: 'sf3_kimetsu', label: '雷鳴とともに現れる、黄色い三角鱗模様の稲妻羽織！', emoji: '⚡', secretTag: 'kimetsu', categoryWeights: { 'スポーティ＆アクティブ': 2, 'クール＆ストリート': 2 } },
      { id: 'sf3_cool', label: '月夜に翻る漆黒マントと、紅の薔薇を胸に差したヴァンパイア！', emoji: '🦇', secretTag: 'secret_cool', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'sf3_pharaoh', label: 'ピラミッドの頂上で黄金に輝く、古代エジプトのファラオ王冠！', emoji: '👑', secretTag: 'pharaoh', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'sf3_girly', label: '湖の月光に照らされる、純白の白鳥フェザーチュチュドレス！', emoji: '🦢', secretTag: 'secret_girly', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
  {
    id: 'sf4',
    genre: 'secret_fate',
    questionText: '心の中に秘めている、あなただけの「隠されたスーパーパワー」は？',
    description: '自分の中に眠っている気がする特別なチカラはどれ？',
    options: [
      { id: 'sf4_kimetsu', label: '心を燃やせ！どんな困難にも立ち向かう熱き炎の闘志！', emoji: '🔥', secretTag: 'kimetsu', categoryWeights: { 'スポーティ＆アクティブ': 2, 'クール＆ストリート': 2 } },
      { id: 'sf4_cosmic', label: '銀河の星々や宇宙の神秘と交信して、未来を見通す力！', emoji: '🌌', secretTag: 'cosmic', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 'sf4_pop', label: '80sディスコの音楽とカセットテープでみんなを踊らせる力！', emoji: '💿', secretTag: 'secret_pop', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'sf4_natural', label: 'アルプスの大自然や動物たちと心を通わせるピュアな優しさ！', emoji: '🏔️', secretTag: 'secret_natural', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'sf5',
    genre: 'secret_fate',
    questionText: '自分専用の「秘密基地」を作れるなら、どこにどんな部屋を作る？',
    description: '放課後やお休みの日にずっと過ごしたい最高の空間は？',
    options: [
      { id: 'sf5_kimetsu', label: '和紙の障子と畳、竹林に囲まれた秘密の修練場・藤の庵！', emoji: '⛩️', secretTag: 'kimetsu', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'sf5_cyber', label: 'クリスタルとネオンライトが光る、ハイテク近未来サイバーラボ！', emoji: '💎', secretTag: 'cyber', categoryWeights: { 'サブカル＆Y2K': 2, 'クール＆ストリート': 2 } },
      { id: 'sf5_girly', label: 'パステルピンクのメリーゴーランドが回る、夢のお姫様サロン！', emoji: '🎠', secretTag: 'secret_girly', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf5_cool', label: 'アンティークな洋館の地下、黒と銀のゴシック読書室！', emoji: '🕸️', secretTag: 'secret_cool', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
  {
    id: 'sf6',
    genre: 'secret_fate',
    questionText: '街を歩いていて、ふとショーウィンドウで一目惚れする伝説のアクセは？',
    description: '見た瞬間に「これ絶対身につけたい！」ってビビッとくるのは？',
    options: [
      { id: 'sf6_kimetsu', label: '麻の葉文様のピンクのリボンと、和風の竹チャーム飾り！', emoji: '🌸', secretTag: 'kimetsu', categoryWeights: { 'スウィート＆ガーリー': 2, 'クラシック＆レトロ': 2 } },
      { id: 'sf6_unicorn', label: '七色にきらめくオーロラクリスタルのペンダント！', emoji: '🦄', secretTag: 'unicorn', categoryWeights: { 'スウィート＆ガーリー': 2, 'ファンタジー＆ドリーム': 2 } },
      { id: 'sf6_pop', label: 'ホログラムの数字が浮かび上がるサイバーバイザー！', emoji: '🎮', secretTag: 'secret_pop', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'sf6_natural', label: '森で採れた押し花と木の実のアンティークブローチ！', emoji: '🌿', secretTag: 'secret_natural', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'sf7',
    genre: 'secret_fate',
    questionText: 'あなたの一番「テンションがMAXに爆上がりする」瞬間は？',
    description: 'ワクワクが止まらなくなっちゃう最高のシチュエーションは？',
    options: [
      { id: 'sf7_kimetsu', label: '仲間と一緒に強敵に立ち向かい、全集中で勝利したとき！', emoji: '⚔️', secretTag: 'kimetsu', categoryWeights: { 'スポーティ＆アクティブ': 3 } },
      { id: 'sf7_magical', label: 'お気に入りのキラキラ服を着て、まるで魔法少女になった気分の日！', emoji: '🪄', secretTag: 'magical', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf7_cool', label: '重低音の音楽に乗って、クールにスケボーやダンスを極めたとき！', emoji: '🎧', secretTag: 'secret_cool', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'sf7_pop', label: '原宿の竹下通りで、カラフルなお菓子やデコラアクセに囲まれたとき！', emoji: '🎈', secretTag: 'secret_pop', categoryWeights: { 'サブカル＆Y2K': 3 } },
    ],
  },
  {
    id: 'sf8',
    genre: 'secret_fate',
    questionText: '異世界からの転生者から「1つだけ魔法の加護」をもらえるならどれがいい？',
    description: 'あなたの一生の宝物になる神秘のチカラは？',
    options: [
      { id: 'sf8_kimetsu', label: 'どんな荒波やピンチも冷静に切り抜ける、水の呼吸の静寂！', emoji: '🌊', secretTag: 'kimetsu', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
      { id: 'sf8_pharaoh', label: '誰もが憧れ敬う、高貴で圧倒的なファラオのカリスマ性！', emoji: '👑', secretTag: 'pharaoh', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'sf8_cosmic', label: '無限に広がる宇宙のように、自由で果てしないひらめきと創造力！', emoji: '🌌', secretTag: 'cosmic', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 'sf8_girly', label: '甘いスイーツと愛されオーラで世界中を笑顔にするスウィートパワー！', emoji: '🧁', secretTag: 'secret_girly', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
  {
    id: 'sf9',
    genre: 'secret_fate',
    questionText: '夜空を見上げたとき、ふと思い浮かべる物語は？',
    description: '星空の向こう側に思いを馳せるならどんな世界？',
    options: [
      { id: 'sf9_cosmic', label: '銀河鉄道に乗って星屑の海を旅する、コズミックファンタジー！', emoji: '🌌', secretTag: 'cosmic', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 'sf9_cool', label: '満月の夜、古城の塔の上で風を受けるミステリアスな物語！', emoji: '🦇', secretTag: 'secret_cool', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'sf9_unicorn', label: '星屑の雲の上で、ユニコーンと眠るパステルドリーム！', emoji: '🦄', secretTag: 'unicorn', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf9_kimetsu', label: '鬼のいない平和な夜明けを目指して、刀を握りしめる剣士たちの絆！', emoji: '⚔️', secretTag: 'kimetsu', categoryWeights: { 'クラシック＆レトロ': 2, 'スポーティ＆アクティブ': 2 } },
    ],
  },
  {
    id: 'sf10',
    genre: 'secret_fate',
    questionText: 'タイムマシンに乗れるなら、どの時代を旅してみたい？',
    description: '歴史の扉を開いて、冒険したい時代を選んでね！',
    options: [
      { id: 'sf10_kimetsu', label: '大正ロマンの浪漫と剣士たちが駆け抜けた、レトロな和の世界！', emoji: '🏯', secretTag: 'kimetsu', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'sf10_pharaoh', label: '金色の砂漠に壮大なピラミッドがそびえる、古代エジプト黄金期！', emoji: '🏛️', secretTag: 'pharaoh', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'sf10_cyber', label: '空飛ぶクルマとアンドロイドが暮らす、西暦3000年のサイバーフューチャー！', emoji: '🚀', secretTag: 'cyber', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'sf10_natural', label: '太古の森でエルフや妖精たちがハーブを紡いでいた、緑の神話時代！', emoji: '🌲', secretTag: 'secret_natural', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'sf11',
    genre: 'secret_fate',
    questionText: '特別な日に食べたい、夢の「ミラクルデザート」は？',
    description: '食べるだけで元気がみなぎる最高のごちそうスイーツは？',
    options: [
      { id: 'sf11_kimetsu', label: '甘露寺蜜璃ちゃんも大好きな、ピンクと緑のつやつや桜餅！', emoji: '🍡', secretTag: 'kimetsu', categoryWeights: { 'スウィート＆ガーリー': 2, 'クラシック＆レトロ': 2 } },
      { id: 'sf11_girly', label: 'あまおう苺を贅沢に重ねた、お姫様ストロベリータワーパフェ！', emoji: '🍓', secretTag: 'secret_girly', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf11_pop', label: '飲むとパチパチ光る、原宿ネオンサイバーブルーソーダ！', emoji: '🥤', secretTag: 'secret_pop', categoryWeights: { 'サブカル＆Y2K': 3 } },
      { id: 'sf11_natural', label: '山奥の隠れ茶房でいただく、摘みたてハーブと野草のシフォンケーキ！', emoji: '🍵', secretTag: 'secret_natural', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'sf12',
    genre: 'secret_fate',
    questionText: '自分が主役の映画が作られるなら、どんなストーリーがいい？',
    description: 'スクリーンいっぱいに大活躍するあなたの物語は？',
    options: [
      { id: 'sf12_kimetsu', label: '和風バトルアクション！仲間との絆と全集中の呼吸で運命を切り拓く超大作！', emoji: '⚔️', secretTag: 'kimetsu', categoryWeights: { 'スポーティ＆アクティブ': 2, 'クラシック＆レトロ': 2 } },
      { id: 'sf12_magical', label: '変身ヒロインファンタジー！歌とキラキラの魔法で世界を救う！', emoji: '🪄', secretTag: 'magical', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf12_cool', label: 'サイバーパンク潜入アクション！華麗にミッションを完遂するクールスパイ！', emoji: '🕶️', secretTag: 'secret_cool', categoryWeights: { 'クール＆ストリート': 3 } },
      { id: 'sf12_pop', label: '原宿カルチャーコメディ！ド派手なファッションで街中を笑顔にする！', emoji: '🎨', secretTag: 'secret_pop', categoryWeights: { 'サブカル＆Y2K': 3 } },
    ],
  },
  {
    id: 'sf13',
    genre: 'secret_fate',
    questionText: '友達に「実は私、〇〇なんだよね…！」と秘密を明かすなら、どれが一番カッコいい？',
    description: '自分だけの秘密の裏の顔！どれに憧れる？',
    options: [
      { id: 'sf13_unicorn', label: '実は夜になると背中にユニコーンの羽が生えて空を飛べる！', emoji: '🦄', secretTag: 'unicorn', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 'sf13_kimetsu', label: '実は代々伝わる剣術道場の跡取りで、日輪刀のお手入れをしている！', emoji: '⚔️', secretTag: 'kimetsu', categoryWeights: { 'クラシック＆レトロ': 2, 'クール＆ストリート': 2 } },
      { id: 'sf13_pharaoh', label: '実は古代エジプト王家の生まれ変わりで、ピラミッドの謎が解ける！', emoji: '👑', secretTag: 'pharaoh', categoryWeights: { 'クラシック＆レトロ': 3 } },
      { id: 'sf13_natural', label: '実は森の動物や草花たちの言葉がすべて聞き分けられる！', emoji: '🧝‍♀️', secretTag: 'secret_natural', categoryWeights: { 'ナチュラル＆ピュア': 3 } },
    ],
  },
  {
    id: 'sf14',
    genre: 'secret_fate',
    questionText: '自分のオーラを色で表すなら、どの輝きがしっくりくる？',
    description: 'あなたの魂が放つ特別な輝きを選んでみて！',
    options: [
      { id: 'sf14_kimetsu', label: '強い信念と優しさを秘めた、深緑と漆黒の市松オーラ！', emoji: '🟩', secretTag: 'kimetsu', categoryWeights: { 'クール＆ストリート': 2, 'クラシック＆レトロ': 2 } },
      { id: 'sf14_unicorn', label: '見る人を元気にする、七色にきらめくレインボーパステルオーラ！', emoji: '🌈', secretTag: 'unicorn', categoryWeights: { 'スウィート＆ガーリー': 2, 'ファンタジー＆ドリーム': 2 } },
      { id: 'sf14_cosmic', label: '夜空と星屑が溶け合う、神秘的なコズミックパープルオーラ！', emoji: '💜', secretTag: 'cosmic', categoryWeights: { 'ファンタジー＆ドリーム': 3 } },
      { id: 'sf14_cool', label: '誰にも染まらない、孤高でシャープなシルバー＆ブラックオーラ！', emoji: '🖤', secretTag: 'secret_cool', categoryWeights: { 'クール＆ストリート': 3 } },
    ],
  },
  {
    id: 'sf15',
    genre: 'secret_fate',
    questionText: '毎日の通学リュックやランドセルに「1つだけ魔法をかける」なら？',
    description: '学校生活が何倍も楽しくなっちゃう秘密の仕掛けは？',
    options: [
      { id: 'sf15_magical', label: '中からいつでも好きなお菓子や可愛いヘアアクセが出てくる魔法！', emoji: '🪄', secretTag: 'magical', categoryWeights: { 'スウィート＆ガーリー': 3 } },
      { id: 'sf15_cyber', label: '背負うだけで重さがゼロになり、電光石火のスピードで走れる魔法！', emoji: '⚡', secretTag: 'cyber', categoryWeights: { 'サブカル＆Y2K': 2, 'スポーティ＆アクティブ': 2 } },
      { id: 'sf15_kimetsu', label: '悪者やイヤなことを寄せ付けない、強力な魔除けと日輪の結界魔法！', emoji: '🗡️', secretTag: 'kimetsu', categoryWeights: { 'クラシック＆レトロ': 2, 'クール＆ストリート': 2 } },
      { id: 'sf15_girly', label: 'その日の気分に合わせて、リボンやお洋服の色が自動で変わる魔法！', emoji: '🎀', secretTag: 'secret_girly', categoryWeights: { 'スウィート＆ガーリー': 3 } },
    ],
  },
];
