import { StyleProfile, StyleTypeId } from '../../domain/models/StyleTypes';

export const PRESET_STYLES: Record<StyleTypeId, StyleProfile> = {
  [StyleTypeId.POP_SPORTY]: {
    typeId: StyleTypeId.POP_SPORTY,
    typeName: '元気ハッピー！ポップスポーティ',
    catchphrase: 'まわりをパッと明るくする太陽のような元気ガール！',
    description: '走ったり体を動かすのが大すき！カラフルで動きやすいアイテムを組み合わせた元気いっぱいなスタイルがぴったり似合います。',
    personalityTraits: ['明るい笑顔', 'アクティブで友だち思い', 'チャレンジ精神ばつぐん'],
    luckyFood: 'ジューシーハンバーグ＆フライドポテト',
    luckyItem: 'ネオンカラーのリストバンドまたはカラフルなヘアゴム',
    recommendedColors: [
      { id: 'c1', name: 'ビタミンイエロー', hex: '#FACC15', description: 'みんなを元気に笑顔にするメインカラー！', isLuckyColor: true },
      { id: 'c2', name: 'アクアスカイブルー', hex: '#38BDF8', description: '青空のようにすっきりさわやかなアクセントカラー。' },
      { id: 'c3', name: 'コーラルオレンジ', hex: '#FB923C', description: '健康的でキュートな印象をプラスするカラー。' },
      { id: 'c4', name: 'スノーホワイト', hex: '#F8FAFC', description: 'カラフルな色を引き締めるクリーンな白。' },
    ],
    hairStyles: [
      {
        id: 'onion_pony',
        name: 'たまねぎポニー（キャンディヘア）',
        tagline: '学校でも体育でも崩れない！ポコポコかわいい定番アレンジ',
        difficulty: 'かんたん',
        durationMinutes: 3,
        suitableLengths: ['medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['細めのシリコンゴム 3〜4本', 'ブラシ'],
        steps: [
          { stepNumber: 1, title: '高い位置でひとつ結び', instruction: '手ぐしやブラシで髪をまとめて、耳より高めの位置でポニーテールを作ります。' },
          { stepNumber: 2, title: '間隔をあけてゴムで留める', instruction: '結んだ毛束の5cmほど下をシリコンゴムで留めます。' },
          { stepNumber: 3, title: 'ふんわり引き出す', instruction: 'ゴムとゴムの間の髪を指先で少しずつ引き出して、丸いたまねぎの形に広げます。' },
          { stepNumber: 4, title: '毛先まで繰り返す', instruction: '髪の長さに合わせて2〜3回繰り返して完成！カラフルゴムを使うとさらにキュート。' },
        ],
      },
      {
        id: 'high_pony_side_braid',
        name: 'サイドねじり高めポニー',
        tagline: '風を切って走っても崩れにくいアクティブポニー！',
        difficulty: 'ふつう',
        durationMinutes: 4,
        suitableLengths: ['medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['ヘアゴム 1本', 'ピン 1〜2本'],
        steps: [
          { stepNumber: 1, title: 'サイドの髪を分ける', instruction: '片側のサイドの髪を少し残して、残りを高めの位置で結びます。' },
          { stepNumber: 2, title: 'サイドをねじる', instruction: '残したサイドの髪を後ろに向かってクルクルねじります。' },
          { stepNumber: 3, title: 'ゴムに巻きつける', instruction: 'ねじった毛束をポニーテールの結び目に巻きつけ、下からピンで留めてゴムを隠します。' },
        ],
      },
    ],
    schoolFashion: {
      id: 'pop_school',
      title: 'ランドセルに映える！アクティブカレッジコーデ',
      scene: '通学・学校',
      summary: '体育の日や休み時間の外遊びも全力で楽しめる、ストレッチ性と可愛さを両立したスクールスタイル！',
      point: 'ポッケ付きショートパンツにレギンスを合わせれば、鉄棒も安心！カレッジロゴTで元気さをアピール。',
      items: [
        { category: 'トップス', name: 'カレッジロゴ入りラグランTシャツ', description: '吸汗速乾で汗をかいてもサラサラ快適', colorSuggestion: 'イエロー×ホワイト' },
        { category: 'ボトムス/ワンピ', name: 'ストレッチデニムショートパンツ＆レギンス', description: '深めポケット付きでハンカチ・ティッシュもしっかり入る', colorSuggestion: 'インディゴブルー' },
        { category: 'くつ/ソックス', name: 'クッションスニーカー＆ラインソックス', description: '走りやすさNo.1の軽量スニーカー', colorSuggestion: 'スカイブルーライン' },
        { category: '小物/アクセ', name: '防水デジタルウォッチ＆星モチーフヘアゴム', description: '校則も安心のシンプルでポップなアイテム', colorSuggestion: 'ビタミンカラー' },
      ],
    },
    weekendFashion: {
      id: 'pop_weekend',
      title: 'テーマパーク＆おでかけPOPスポーティコーデ',
      scene: '休日・おでかけ',
      summary: 'ビビッドな差し色がおしゃれな、お友達や家族とのおでかけスタイル！',
      point: 'キャップとウエストポーチで両手をあけて、軽快におしゃれ度アップ！',
      items: [
        { category: 'トップス', name: 'バイカラーのフード付きウインドブレーカー', description: '日焼け防止や急な気温変化にも強いシャカシャカ素材', colorSuggestion: 'ミント×オレンジ' },
        { category: 'ボトムス/ワンピ', name: 'サイドライン入りスウェットスカート（インナーパンツ付き）', description: 'かわいさと動きやすさを両立', colorSuggestion: 'ヘザーグレー' },
        { category: 'くつ/ソックス', name: 'ボリュームソールの厚底風スニーカー', description: 'クッションが効いて足が疲れにくい', colorSuggestion: 'ホワイト×ネオン' },
        { category: '小物/アクセ', name: 'ロゴ刺繍キャップ＆ミニボディバッグ', description: 'お小遣いや水筒も持ち歩きやすい', colorSuggestion: 'ネイビー' },
      ],
    },
  },

  [StyleTypeId.SWEET_GIRLY]: {
    typeId: StyleTypeId.SWEET_GIRLY,
    typeName: 'ふんわり夢みる！スウィートガーリー',
    catchphrase: 'まるで物語のプリンセス！優しく可憐な愛されガール！',
    description: 'リボンやフリル、淡いパステルカラーが大すき。お上品で甘くかわいい世界観があなたの上品な魅力を引き立てます。',
    personalityTraits: ['やさしく思いやりがある', 'かわいい小物集めが好き', '丁寧で上品'],
    luckyFood: 'いちごのパフェ＆ふわふわスフレパンケーキ',
    luckyItem: 'サテンリボンのヘアゴムやパステルチャーム',
    recommendedColors: [
      { id: 'c1', name: 'ミルキーラベンダー', hex: '#C084FC', description: 'お上品で幻想的な透明感を引き出すメインカラー！', isLuckyColor: true },
      { id: 'c2', name: 'ベビーブロッサムピンク', hex: '#F472B6', description: 'お花のように愛らしい華やかさを添えるピンク。' },
      { id: 'c3', name: 'ホイップホワイト', hex: '#FFF1F2', description: 'やわらかく包み込むようなやさしい白。' },
      { id: 'c4', name: 'ミントシフォン', hex: '#6EE7B7', description: '甘くなりすぎない爽やかなアクセント。' },
    ],
    hairStyles: [
      {
        id: 'kururinpa_half',
        name: 'くるりんぱハーフアップ',
        tagline: 'たった1分で魔法がかかる！お姫さま風ハーフアップ',
        difficulty: 'かんたん',
        durationMinutes: 2,
        suitableLengths: ['medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['細めのシリコンゴム 1本', '小さなリボンゴム（学校ならシンプルなもの）'],
        steps: [
          { stepNumber: 1, title: '耳上の髪を取る', instruction: '耳の上の髪を少し取って、後頭部の真ん中でゆるめにゴムで結びます。' },
          { stepNumber: 2, title: '結び目の上にすき間を作る', instruction: 'ゴムのすぐ上の髪を指で左右に割って、小さな穴を作ります。' },
          { stepNumber: 3, title: '毛束をくるりんぱ！', instruction: '毛束を上からその穴に通して下に引き抜きます。' },
          { stepNumber: 4, title: 'キュッと締めてほぐす', instruction: '毛束を左右に引っ張ってゴムを締め、ねじれた部分の髪を少し引き出してふんわりさせます。' },
        ],
      },
      {
        id: 'side_braid_ribbon',
        name: 'サイドみつあみリボン留め',
        tagline: '横顔がかわいく映える！帽子もかぶりやすいアレンジ',
        difficulty: 'かんたん',
        durationMinutes: 3,
        suitableLengths: ['short', 'medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['ヘアピン 2本', '細めシリコンゴム 1本'],
        steps: [
          { stepNumber: 1, title: '分け目から編み始める', instruction: '前髪の横の髪をすくい、耳の後ろに向かって三つ編みを作ります。' },
          { stepNumber: 2, title: '耳の後ろでピン留め', instruction: '耳の後ろあたりで三つ編みをピンでクロス留めします。' },
          { stepNumber: 3, title: '編み目を軽くほぐす', instruction: '三つ編みの外側を少しずつつまんで広げると、ふんわりロマンチックに！' },
        ],
      },
    ],
    schoolFashion: {
      id: 'sweet_school',
      title: 'フリル襟とパステルで清楚！スウィート通学コーデ',
      scene: '通学・学校',
      summary: '控えめなフリルやパステルカラーを取り入れ、校則にもぴったりの上品スクールスタイル！',
      point: 'ポシェットを付けられるベルトループやハンカチポケットがついた、スカパン（スカート見えパンツ）が安心＆可愛い！',
      items: [
        { category: 'トップス', name: '控えめレース襟付きリブカットソー', description: '伸縮性があって着心地らくらく、洗濯機洗いも安心', colorSuggestion: 'オフホワイト' },
        { category: 'ボトムス/ワンピ', name: 'くすみラベンダーのプリーツスカパン', description: 'インナーパンツ付きで階段や鉄棒も安心なスカート風', colorSuggestion: 'ラベンダー' },
        { category: 'くつ/ソックス', name: 'バックリボン付きクルーソックス＆きれいめスニーカー', description: 'かかとにさりげないリボンが可愛い', colorSuggestion: 'ライトピンク' },
        { category: '小物/アクセ', name: '移動ポケット（マルチポケット）＆パステルリボンゴム', description: 'ハンカチ・ティッシュをかわいく携帯', colorSuggestion: 'ミルキーピンク' },
      ],
    },
    weekendFashion: {
      id: 'sweet_weekend',
      title: 'ふわふわチュールのプリンセスおでかけコーデ',
      scene: '休日・おでかけ',
      summary: 'お誕生日やカフェ、ショッピングにぴったりの華やかスイートスタイル！',
      point: 'チュール重ねのワンピースにカーディガンを羽織って、上品なお嬢様気分に！',
      items: [
        { category: 'ボトムス/ワンピ', name: '小花柄ドッキングチュールワンピース', description: '一枚でコーディネートが完成する主役級ワンピ', colorSuggestion: 'パステルピンク×ホワイト' },
        { category: 'アウター', name: 'ビジューボタンの丸首ニットカーディガン', description: 'きらきらボタンがアクセント', colorSuggestion: 'ミルキーホワイト' },
        { category: 'くつ/ソックス', name: 'エナメル調ストラップシューズ（メリージェーン）', description: '脱げにくく歩きやすいマジックテープ仕様', colorSuggestion: 'シャイニーピンク' },
        { category: '小物/アクセ', name: 'パール調チェーンのミニショルダーバッグ', description: 'リップやハンカチが入るミニサイズ', colorSuggestion: 'アイボリー' },
      ],
    },
  },

  [StyleTypeId.COOL_CASUAL]: {
    typeId: StyleTypeId.COOL_CASUAL,
    typeName: 'さわやか大人っぽ！クールカジュアル',
    catchphrase: 'シンプルなのに洗練された、みんなの憧れかっこいい系女子！',
    description: '甘すぎるのはちょっと苦手。デニムやシンプルなシルエット、モノトーンやすっきりブルーが得意なスタイルです。',
    personalityTraits: ['頼りがいがある', '落ち着いていてクール', '自分らしさを大切にする'],
    luckyFood: 'パリッとピザ＆具だくさんサンドイッチ',
    luckyItem: 'シンプルシルバーピンまたはロゴ入りキャンバストート',
    recommendedColors: [
      { id: 'c1', name: 'ディープネイビー', hex: '#1E3A8A', description: '知性と落ち着きを演出するベースカラー。', isLuckyColor: true },
      { id: 'c2', name: 'アイスシルバーグレー', hex: '#94A3B8', description: 'どんな服にも合わせやすいスマートな中間色。' },
      { id: 'c3', name: 'エメラルドシアン', hex: '#06B6D4', description: 'キリッとしたアクセントを与える涼やかなブルー。' },
      { id: 'c4', name: 'ピュアブラック', hex: '#0F172A', description: '全体のシルエットをスタイリッシュに引き締める黒。' },
    ],
    hairStyles: [
      {
        id: 'low_pony_pins',
        name: '低めローポニー＋ゴールドクロスピン',
        tagline: 'こなれ感バツグン！すっきり大人っぽいクールポニー',
        difficulty: 'かんたん',
        durationMinutes: 2,
        suitableLengths: ['medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['太め黒ゴム 1本', 'ヘアピン 2本'],
        steps: [
          { stepNumber: 1, title: '襟足近くでタイトに結ぶ', instruction: 'くしで毛流れを整えて、首の根元の位置できれいに結びます。' },
          { stepNumber: 2, title: 'トップを少しだけ引き出す', instruction: '頭頂部の髪を3箇所ほど細かく引き出して立体感を作ります。' },
          { stepNumber: 3, title: 'サイドにピンをクロス留め', instruction: '耳の上にピンを「×」の形になるようにクロスして留めます。' },
        ],
      },
      {
        id: 'neat_half_twist',
        name: 'すっきりサイドねじりピン留め',
        tagline: '短めボブでもOK！前髪もすっきり涼しげスタイル',
        difficulty: 'かんたん',
        durationMinutes: 2,
        suitableLengths: ['short', 'medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['アメリカピン 2本'],
        steps: [
          { stepNumber: 1, title: '前髪やサイドを取る', instruction: '顔周りの髪を少量取って、後ろ方向へキュッと強めにねじります。' },
          { stepNumber: 2, title: 'ピンを奥から差し込む', instruction: 'ねじった毛先を耳の上でしっかりピンで固定します。' },
        ],
      },
    ],
    schoolFashion: {
      id: 'cool_school',
      title: 'スマート＆動きやすい！ワイドストレートデニムコーデ',
      scene: '通学・学校',
      summary: '足長効果バツグンのワイドパンツとシンプルロンTで、大人っぽく垢抜けた印象に！',
      point: '裾がもたつかない丈感のパンツを選べば、階段の上り下りや掃除の時間も快適！',
      items: [
        { category: 'トップス', name: 'バックプリント入りオーバーサイズロンT', description: '着丈長めでゆったり着心地がいい', colorSuggestion: 'チャコールグレー' },
        { category: 'ボトムス/ワンピ', name: 'ウエストゴムのストレートワイドデニム', description: '脱ぎ履き簡単で動きやすいストレッチデニム', colorSuggestion: 'ウォッシュネイビー' },
        { category: 'くつ/ソックス', name: 'モノトーンローカットスニーカー', description: 'どんな服にも似合う万能シューズ', colorSuggestion: 'ブラック×ホワイト' },
        { category: '小物/アクセ', name: 'シンプルロゴ入りメッシュペンケース＆モノトーンゴム', description: '授業中も邪魔にならない実用派アクセ', colorSuggestion: 'シルバー/ブラック' },
      ],
    },
    weekendFashion: {
      id: 'cool_weekend',
      title: 'ストリート風マウンテンパーカースタイル',
      scene: '休日・おでかけ',
      summary: '都会的なストリートカジュアルで、お買い物や映画館へGO！',
      point: '短め丈のアウターとハイウエストパンツでバランス感抜群のスタイルアップ。',
      items: [
        { category: 'アウター', name: 'ショート丈マウンテンパーカー', description: '撥水防風でかっこいいシルエット', colorSuggestion: 'カーキグリーン' },
        { category: 'ボトムス/ワンピ', name: 'カーゴジョガーパンツ', description: '裾がリブになっていてスニーカーが引き立つ', colorSuggestion: 'ブラック' },
        { category: 'くつ/ソックス', name: 'ハイテクスニーカー', description: '厚みのあるソールでトレンド感UP', colorSuggestion: 'ホワイト×グレー' },
        { category: '小物/アクセ', name: 'バケットハット＆ショルダーサコッシュ', description: '日差し対策もおしゃれに決まる', colorSuggestion: 'ブラック' },
      ],
    },
  },

  [StyleTypeId.NATURAL_PURE]: {
    typeId: StyleTypeId.NATURAL_PURE,
    typeName: 'やさしいお姉さん！ナチュラルピュア',
    catchphrase: 'ほんわか自然体で清潔感あふれる、癒やしのナチュラルガール！',
    description: 'アースカラーや麻・コットン素材、落ち着いたチェック柄がよく似合う、やさしく清潔感のあるスタイルです。',
    personalityTraits: ['聞き上手で穏やか', '読書や生き物が好き', '自然体で気取らない'],
    luckyFood: '具だくさんお味噌汁＆焼きたてクロワッサン',
    luckyItem: 'ウッド調ヘアゴムまたはリネンハンカチ',
    recommendedColors: [
      { id: 'c1', name: 'セージグリーン', hex: '#84CC16', description: '若草のような爽やかさと落ち着きをくれる癒やしカラー。', isLuckyColor: true },
      { id: 'c2', name: 'ミルクティーベージュ', hex: '#FDE047', description: 'やわらかく包み込むような温もりのあるベージュ。' },
      { id: 'c3', name: 'アイボリーホワイト', hex: '#FAFAF9', description: '天然素材のようにピュアで優しい白。' },
      { id: 'c4', name: 'テラコッタブラウン', hex: '#B45309', description: '土や木のような安心感を与えるアクセントカラー。' },
    ],
    hairStyles: [
      {
        id: 'loose_side_braid',
        name: 'ふんわりサイド三つ編み',
        tagline: '帽子もすっぽり！やさしい風合いのサイド編み',
        difficulty: 'かんたん',
        durationMinutes: 3,
        suitableLengths: ['medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['茶色またはベージュのシリコンゴム 1本'],
        steps: [
          { stepNumber: 1, title: '髪を片側に寄せる', instruction: '左右どちらかの耳の下に髪を全部集めます。' },
          { stepNumber: 2, title: 'ゆるく三つ編みをする', instruction: 'きつく締めすぎず、リラックスして毛先まで編みます。' },
          { stepNumber: 3, title: '毛先をゴムで結ぶ', instruction: '毛先を3cmほど残してゴムで留めます。' },
          { stepNumber: 4, title: '編み目を優しく引き出す', instruction: '編み目を指の腹で外側に優しく広げて、ナチュラルな抜け感を出します。' },
        ],
      },
    ],
    schoolFashion: {
      id: 'natural_school',
      title: 'コットンの風合いで爽やか！ナチュラル通学スタイル',
      scene: '通学・学校',
      summary: '肌触りの良い天然コットン素材で一日中気持ちよく過ごせるスクールコーデ！',
      point: '清潔感あふれるスタンドカラー風シャツとチノ風パンツで、先生やお友達からも好印象！',
      items: [
        { category: 'トップス', name: 'スタンドカラーのコットンブラウスTシャツ', description: 'きちんと感がありつつカットソー素材で動きやすい', colorSuggestion: 'アイボリー' },
        { category: 'ボトムス/ワンピ', name: 'ストレッチツイルのゆったりテーパードパンツ', description: '座りっぱなしの授業でもお腹が苦しくないゴム仕様', colorSuggestion: 'ベージュ' },
        { category: 'くつ/ソックス', name: 'キャンバススリッポン＆リブソックス', description: '脱ぎ履きしやすく靴箱での履き替えもスピーディ', colorSuggestion: 'オリーブグリーン' },
        { category: '小物/アクセ', name: '刺繍入りハンドタオル＆ウッドビーズ風ヘアゴム', description: '優しい手触りのナチュラル小物', colorSuggestion: 'ブラウン' },
      ],
    },
    weekendFashion: {
      id: 'natural_weekend',
      title: 'ピクニックや図書館へ行きたくなる！チェック柄サロペット',
      scene: '休日・おでかけ',
      summary: '休日のお散歩やブックカフェにぴったりのリラックスおでかけスタイル！',
      point: 'チェック柄サロペットにリブニットを合わせて、ほっこり可愛らしいシルエットに。',
      items: [
        { category: 'ボトムス/ワンピ', name: 'ギンガムチェック柄のコットンサロペット', description: 'ゆったり着られて肩紐調整可能なワイドシルエット', colorSuggestion: 'ベージュ×ブラウン' },
        { category: 'トップス', name: 'やわらかリブのクルーネック長袖T', description: 'インナーとしても一枚でも着回し力抜群', colorSuggestion: 'エクリュ' },
        { category: 'くつ/ソックス', name: 'レザーライクなコンフォートシューズ', description: '長時間歩いても足裏が痛くなりにくい設計', colorSuggestion: 'キャメル' },
        { category: '小物/アクセ', name: 'ジュート風ミニトートバッグ', description: '文庫本やスケッチブックを入れておでかけ', colorSuggestion: 'ナチュラル' },
      ],
    },
  },

  [StyleTypeId.TRENDY_IDOL]: {
    typeId: StyleTypeId.TRENDY_IDOL,
    typeName: 'キラキラ主役級！トレンドおしゃかわアイドル',
    catchphrase: 'SNSや雑誌の流行をキャッチ！どこにいても輝く憧れの的！',
    description: '流行りのK-POP風や原宿系、おしゃれな重ね着や小物が大好き！まわりと一味違うトレンドスタイルで注目の的です。',
    personalityTraits: ['トレンドに敏感', '写真やダンスが好き', '自己プロデュース上手'],
    luckyFood: 'レインボーマカロン＆タピオカミルクティー',
    luckyItem: 'オーロラハートのヘアクリップやアームウォーマー',
    recommendedColors: [
      { id: 'c1', name: 'オーロラライラック', hex: '#A855F7', description: '光を浴びてキラキラ輝く主役カラー！', isLuckyColor: true },
      { id: 'c2', name: 'ビビッドチェリーピンク', hex: '#EC4899', description: 'ポップで視線を集めるキュートなアクセント。' },
      { id: 'c3', name: 'シャイニーシルバー', hex: '#CBD5E1', description: '近未来感と透明感をプラスするトレンドカラー。' },
      { id: 'c4', name: 'ピュアホワイト', hex: '#FFFFFF', description: 'どんな鮮やかな色も引き立てる万能ベース。' },
    ],
    hairStyles: [
      {
        id: 'kuma_mimi_buns',
        name: 'ツインおだんご（くま耳ヘア）',
        tagline: 'ダンスやおでかけで大注目！キュートなくま耳スタイル',
        difficulty: 'ふつう',
        durationMinutes: 4,
        suitableLengths: ['medium', 'long'],
        isSchoolOk: false,
        itemsNeeded: ['ヘアゴム 2本', 'Uピン 2〜4本'],
        steps: [
          { stepNumber: 1, title: '高い位置でツインテール', instruction: '左右対称に、耳の上やや後ろの高い位置でツインテールを作ります。' },
          { stepNumber: 2, title: '毛束をねじってくるくる巻く', instruction: '毛束をしっかりねじりながら、結び目の周りに丸く巻きつけます。' },
          { stepNumber: 3, title: 'ピンで留めてほぐす', instruction: '毛先をピンでしっかり固定し、おだんごを少しつまんで丸くふっくら整えます。' },
        ],
      },
      {
        id: 'heart_clip_twins',
        name: '高めハーフツイン＋ミニクリップ',
        tagline: '学校でもOK！アイドルみたいな軽やかハーフツイン',
        difficulty: 'かんたん',
        durationMinutes: 3,
        suitableLengths: ['short', 'medium', 'long'],
        isSchoolOk: true,
        itemsNeeded: ['細めシリコンゴム 2本', 'ミニヘアクリップ（学校なら校則に合わせたピン）'],
        steps: [
          { stepNumber: 1, title: 'トップの髪を左右に分ける', instruction: '頭頂部の髪を左右に分け、斜め上の位置で結びます。' },
          { stepNumber: 2, title: '根元をキュッと締める', instruction: '結び目を少しきつめに締めて、ピョコッと立ち上がらせます。' },
          { stepNumber: 3, title: '結び目の前にクリップをパチン', instruction: '結び目の少し前にミニクリップをつけてアクセントに！' },
        ],
      },
    ],
    schoolFashion: {
      id: 'idol_school',
      title: 'プレッピー風！チルデンベスト＆チェックスカパン',
      scene: '通学・学校',
      summary: '制服風のきちんと感と韓国っぽトレンドを組み合わせた、校則OKの優等生アイドルコーデ！',
      point: 'プリーツスカパンなら風が強い日も安心！ベストのラインが写真写りもバッチリ良くしてくれます。',
      items: [
        { category: 'トップス', name: 'ライン入りチルデンベスト＆白シャツ風カットソー', description: '重ね着風で一枚で着られる時短アイテム', colorSuggestion: 'ネイビー×ホワイト' },
        { category: 'ボトムス/ワンピ', name: 'タータンチェック柄プリーツスカパン', description: 'インナーパンツ付き＆後ろゴム仕様', colorSuggestion: 'グレー×パープルチェック' },
        { category: 'くつ/ソックス', name: 'リブハイソックス＆厚底スニーカー', description: '足元をすらっと見せる美脚バランス', colorSuggestion: 'ホワイト' },
        { category: '小物/アクセ', name: 'スクールリボン風チャーム付きリュック', description: '教科書もタブレットもすっぽり入る大容量', colorSuggestion: 'ラベンダー' },
      ],
    },
    weekendFashion: {
      id: 'idol_weekend',
      title: 'K-POPダンス風！クロップドパーカー＆カーゴスカート',
      scene: '休日・おでかけ',
      summary: 'お友達とのおそろコーデやダンスレッスンにも映える、最先端ストリートアイドルスタイル！',
      point: '少し短め丈のパーカーとボリューミーなカーゴスカートで、メリハリのある旬シルエット！',
      items: [
        { category: 'トップス', name: 'ハーフジップのショート丈スウェット', description: 'ジップの開き具合でインナー見せもおしゃれ', colorSuggestion: 'オーロラピンク' },
        { category: 'ボトムス/ワンピ', name: 'サイドビッグポケット付きカーゴロングスカート', description: 'スリット入りで足さばき抜群', colorSuggestion: 'シルバーグレー' },
        { category: 'くつ/ソックス', name: 'ダッドスニーカー＆ルーズソックス風くしゅくしゅ靴下', description: 'ボリューム感で足首細見え効果', colorSuggestion: 'ホワイト' },
        { category: '小物/アクセ', name: 'キラキラヘッドホン風カチューシャ＆オーロラショルダー', description: '写真映え度120%の注目アイテム', colorSuggestion: 'オーロラシルバー' },
      ],
    },
  },
};
