import { LuckyItem } from './FortuneTypes';

export const LUCKY_ITEMS_100: LuckyItem[] = [
  // 1-20: ステーショナリー・文房具 (20個)
  {
    id: 1,
    name: 'キラキララメペン',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '✨',
    luckyColor: 'ゴールド',
    advice: 'ノートのタイトルをキラキラにするとやる気アップ！',
  },
  {
    id: 2,
    name: 'グラデーション消しゴム',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🫧',
    luckyColor: 'パステルブルー',
    advice: '角から使うと小さなミスもキレイさっぱりリセット♪',
  },
  {
    id: 3,
    name: 'ハートのクリップ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '📎',
    luckyColor: 'チェリーピンク',
    advice: '大切なプリントをまとめると忘れ物ゼロになれるよ！',
  },
  {
    id: 4,
    name: 'パステルふせん',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '📑',
    luckyColor: 'ミントグリーン',
    advice: '友達へのメモに使うと友情度がグンと深まりそう！',
  },
  {
    id: 5,
    name: 'もこもこペンケース',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '👝',
    luckyColor: 'ラベンダー',
    advice: '手触りの良さで勉強の合間にリフレッシュしてね。',
  },
  {
    id: 6,
    name: '定規キーホルダー',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '📏',
    luckyColor: 'クリアイエロー',
    advice: 'きっちり測って行動するとラッキーチャンスをつかめるよ！',
  },
  {
    id: 7,
    name: 'マスキングテープ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🎗️',
    luckyColor: 'コーラルピンク',
    advice: '手帳やノートをデコって自分らしさをアピールしよう♪',
  },
  {
    id: 8,
    name: 'フルーティーな香りのマーカー',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🖍️',
    luckyColor: 'ストロベリーレッド',
    advice: 'いい香りで周りのみんなもハッピーにしちゃおう！',
  },
  {
    id: 9,
    name: 'ゆらゆらチャーム付きシャープペン',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '✏️',
    luckyColor: 'シルバー',
    advice: '書くたびに揺れるチャームが幸運を呼び込んでくれるよ。',
  },
  {
    id: 10,
    name: 'くまさんダイカットメモ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🧸',
    luckyColor: 'ミルクティーベージュ',
    advice: '今日のToDoをメモしてひとつずつクリアしてみて！',
  },
  {
    id: 11,
    name: 'ホログラムシール',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🌟',
    luckyColor: 'レインボー',
    advice: '光に反射する輝きが、あなたの自信を引き出してくれるよ！',
  },
  {
    id: 12,
    name: 'スライダー付きクリアファイル',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '📂',
    luckyColor: 'スカイブルー',
    advice: 'カバンの中が整うと、気持ちもスッキリ前向きになれる！',
  },
  {
    id: 13,
    name: '星型浸透スタンプ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '⭐',
    luckyColor: 'レモンイエロー',
    advice: '頑張ったノートにポンと押して自分をほめてあげてね。',
  },
  {
    id: 14,
    name: 'スケジュールシール帳',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '📒',
    luckyColor: 'ピーチピンク',
    advice: 'これからの予定をワクワク想像すると夢が近づくよ♪',
  },
  {
    id: 15,
    name: 'パステル修正テープ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🩹',
    luckyColor: 'ピュアホワイト',
    advice: '失敗してもやり直せば大丈夫！何度でもトライしよう。',
  },
  {
    id: 16,
    name: '安全キャップ付きミニハサミ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '✂️',
    luckyColor: 'ベビーピンク',
    advice: '工作や切り抜きで新しいアイデアがパッとひらめきそう！',
  },
  {
    id: 17,
    name: '動物インデックスシール',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🐱',
    luckyColor: 'オレンジ',
    advice: 'ピョコッと出る可愛い動物たちが癒やしをくれるよ。',
  },
  {
    id: 18,
    name: 'カラーシャープ芯（ミント）',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🌱',
    luckyColor: 'ミントグリーン',
    advice: 'いつもと違う色で書くと、新しい発見がいっぱい！',
  },
  {
    id: 19,
    name: '金属製リボンブックマーカー',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🔖',
    luckyColor: 'ローズゴールド',
    advice: 'お気に入りの本を開くたび、素敵なヒントが見つかりそう。',
  },
  {
    id: 20,
    name: 'ぽんぽんデコレーションテープ',
    category: 'stationery',
    categoryLabel: '文房具',
    emoji: '🎨',
    luckyColor: 'ビビッドピンク',
    advice: 'ノートをカラフルに彩って、今日の主役になっちゃおう！',
  },

  // 21-40: アクセサリー＆ヘア小物 (20個)
  {
    id: 21,
    name: 'サテン素材の大きめシュシュ',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '🎀',
    luckyColor: 'シャンパンピンク',
    advice: '手首につけておくだけでも華やかオーラ全開に！',
  },
  {
    id: 22,
    name: 'パール付きヘアピン',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '🤍',
    luckyColor: 'パールホワイト',
    advice: 'サイドの髪を留めて上品な大人っぽさを演出してみて。',
  },
  {
    id: 23,
    name: 'ビーズブレスレット',
    category: 'accessory',
    categoryLabel: 'アクセサリー',
    emoji: '📿',
    luckyColor: 'ターコイズ',
    advice: '友達とおそろいや色違いでつけると友情運アップ！',
  },
  {
    id: 24,
    name: 'ハートチャームのヘアゴム',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '💖',
    luckyColor: 'ルビーレッド',
    advice: 'ポニーテールを揺らすたびにハッピーを引き寄せるよ。',
  },
  {
    id: 25,
    name: 'カラーパッチン留め',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '🌈',
    luckyColor: 'ネオンイエロー',
    advice: '2個並べてつけると今っぽトレンド感が急上昇！',
  },
  {
    id: 26,
    name: 'ベロアカチューシャ',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '👑',
    luckyColor: 'ディープネイビー',
    advice: 'すっきりおでこを出すと明るい笑顔がみんなに届くよ。',
  },
  {
    id: 27,
    name: '蝶々モチーフのミニクリップ',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '🦋',
    luckyColor: 'ライラックパープル',
    advice: '軽やかな蝶々のように、フットワーク軽く行動してね！',
  },
  {
    id: 28,
    name: 'デイジーのお花ヘアゴム',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '🌼',
    luckyColor: 'サンシャインイエロー',
    advice: 'お日様のような明るさでみんなの中心になれそう♪',
  },
  {
    id: 29,
    name: 'ギンガムチェックのリボン',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '🎀',
    luckyColor: 'フレンチレッド',
    advice: 'ガーリーなチェック柄が愛され度をアップしてくれる！',
  },
  {
    id: 30,
    name: 'フリル付きショートソックス',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '🧦',
    luckyColor: 'オフホワイト',
    advice: '足元まで気を抜かないおしゃれで歩くのが楽しみに♪',
  },
  {
    id: 31,
    name: 'キラキララメソックス',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '✨',
    luckyColor: 'シルバーグレー',
    advice: 'スニーカーからのぞくラメが今日の隠れたアクセント！',
  },
  {
    id: 32,
    name: 'エナメルピンバッジ',
    category: 'accessory',
    categoryLabel: 'アクセサリー',
    emoji: '📛',
    luckyColor: 'フォレストグリーン',
    advice: 'キャップやリュックにつけて自分だけのスタイルを作ろう。',
  },
  {
    id: 33,
    name: 'キルティングミニポシェット',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '👛',
    luckyColor: 'アイボリー',
    advice: 'お気に入りだけを詰め込んでお散歩に出かけよう！',
  },
  {
    id: 34,
    name: 'くまさんアクリルリング',
    category: 'accessory',
    categoryLabel: 'アクセサリー',
    emoji: '💍',
    luckyColor: 'キャンディピンク',
    advice: '手元を見るたびにキュートな笑顔になれるお守りリング。',
  },
  {
    id: 35,
    name: 'クリアオーロラポーチ',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '👝',
    luckyColor: 'オーロラ',
    advice: '光の角度で色が変わるポーチがインスピレーションを刺激！',
  },
  {
    id: 36,
    name: 'スニーカーチャーム（ハート型）',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '👟',
    luckyColor: 'メタリックピンク',
    advice: '靴ひもに通して足元から元気なステップを踏み出そう！',
  },
  {
    id: 37,
    name: 'ふわふわイヤーマフ',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '🎧',
    luckyColor: 'スノーホワイト',
    advice: 'あたたかさと小顔効果で冬のおしゃれ度ナンバーワン！',
  },
  {
    id: 38,
    name: 'ロゴ入りリストバンド',
    category: 'accessory',
    categoryLabel: 'アクセサリー',
    emoji: '💪',
    luckyColor: 'アクアブルー',
    advice: 'スポーティな元気スタイルでアクティブに過ごそう。',
  },
  {
    id: 39,
    name: 'キラキラビジューのバンスクリップ',
    category: 'accessory',
    categoryLabel: 'ヘアアクセ',
    emoji: '💎',
    luckyColor: 'クリスタル',
    advice: 'サッと髪をまとめるだけで大人っぽい抜け感が完成！',
  },
  {
    id: 40,
    name: 'レースのつけ襟',
    category: 'accessory',
    categoryLabel: 'ファッション小物',
    emoji: '👗',
    luckyColor: 'アンティークレース',
    advice: 'シンプルな服に重ねるだけでお姫様気分になれるよ。',
  },

  // 41-55: おやつ＆フード (15個)
  {
    id: 41,
    name: 'いちごのショートケーキ',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍰',
    luckyColor: 'ストロベリーレッド',
    advice: '甘酸っぱさとふんわりクリームでごきげんMAX♪',
  },
  {
    id: 42,
    name: 'パステルカラーのマカロン',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🧁',
    luckyColor: 'パステルグリーン',
    advice: 'サクッ＆しっとり食感で特別なティータイム気分に！',
  },
  {
    id: 43,
    name: 'もちもちタピオカミルクティー',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🧋',
    luckyColor: 'ロイヤルブラウン',
    advice: 'お気に入りのトッピングでエネルギーをチャージしてね。',
  },
  {
    id: 44,
    name: 'プリンアラモード',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍮',
    luckyColor: 'カスタードイエロー',
    advice: 'フルーツいっぱいの豪華デザートで贅沢なご褒美を！',
  },
  {
    id: 45,
    name: 'カラフルグミキャンディ',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍬',
    luckyColor: 'マルチカラー',
    advice: '噛むほどに広がるフルーティーな味で集中力UP！',
  },
  {
    id: 46,
    name: 'チョコチップクッキー',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍪',
    luckyColor: 'ココアブラウン',
    advice: '友達と半分こすると楽しさが2倍にふくらむよ♪',
  },
  {
    id: 47,
    name: 'しゅわしゅわメロンクリームソーダ',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍨',
    luckyColor: 'エメラルドグリーン',
    advice: 'チェリーを最後に食べるか最初に食べるかでワクワク！',
  },
  {
    id: 48,
    name: 'いちごチョコディップドーナツ',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍩',
    luckyColor: 'ポップピンク',
    advice: '丸いドーナツは円満のしるし。みんなと仲良しになれるよ！',
  },
  {
    id: 49,
    name: 'キャラメルポップコーン',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍿',
    luckyColor: 'キャラメルオレンジ',
    advice: '映画や読書のお供にぴったり。楽しい発見がありそう！',
  },
  {
    id: 50,
    name: 'レインボーかき氷',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍧',
    luckyColor: 'レインボー',
    advice: 'いろんなシロップが混ざり合って最高の味になるよ。',
  },
  {
    id: 51,
    name: 'ふんわりマシュマロトースト',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍞',
    luckyColor: 'マシュマロホワイト',
    advice: 'とろける甘さで疲れた心を優しく癒やしてあげて。',
  },
  {
    id: 52,
    name: 'ベリーワッフル',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🧇',
    luckyColor: 'ベリーパープル',
    advice: 'サクサクのワッフルが今日の元気の源になってくれる！',
  },
  {
    id: 53,
    name: 'シナモンチュロス',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🥖',
    luckyColor: 'シナモンベージュ',
    advice: 'テーマパークに来たようなウキウキ気分を楽しもう。',
  },
  {
    id: 54,
    name: '濃厚バニラソフトクリーム',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍦',
    luckyColor: 'ミルクホワイト',
    advice: 'くるくる巻かれた形のように運気もうなぎ登り！',
  },
  {
    id: 55,
    name: 'ぷるぷるピーチゼリー',
    category: 'sweets',
    categoryLabel: 'おやつ',
    emoji: '🍑',
    luckyColor: 'ピーチピンク',
    advice: 'みずみずしい果汁で心もお肌もツヤツヤに♪',
  },

  // 56-70: 持ち物・お出かけグッズ (15個)
  {
    id: 56,
    name: 'コンパクト折りたたみミラー',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🪞',
    luckyColor: 'シルバーピンク',
    advice: '鏡を見るときはニッコリ笑顔を作ってみて！',
  },
  {
    id: 57,
    name: 'いちご香るリップクリーム',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '💄',
    luckyColor: 'コーラルレッド',
    advice: 'うるおう唇で話すと、言葉がもっと温かく伝わるよ。',
  },
  {
    id: 58,
    name: 'フローラルハンドクリーム',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🧴',
    luckyColor: 'パステルラベンダー',
    advice: '手肌をケアして指先までキラキラ輝かせよう。',
  },
  {
    id: 59,
    name: 'くし付き折りたたみヘアブラシ',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🪮',
    luckyColor: 'サックスブルー',
    advice: '休み時間にサッと髪をとかしていつでも清潔感キープ！',
  },
  {
    id: 60,
    name: 'シリコンホルダー付き除菌ジェル',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🧼',
    luckyColor: 'ライムグリーン',
    advice: 'リュックにぶら下げていつでも清潔安心♪',
  },
  {
    id: 61,
    name: 'もこもこ水筒カバー',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🍶',
    luckyColor: 'モカブラウン',
    advice: 'しっかり水分補給をして一日中元気に過ごしてね！',
  },
  {
    id: 62,
    name: 'キラリと光るリフレクターキーホルダー',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '✨',
    luckyColor: 'ネオングリーン',
    advice: '夕暮れ道も安全第一！あなたを優しく守ってくれるよ。',
  },
  {
    id: 63,
    name: 'リール付きパスケース',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🎫',
    luckyColor: 'スカイブルー',
    advice: '改札やバスでもたつかずスマートに行動できそう！',
  },
  {
    id: 64,
    name: 'コンパクトエコバッグ',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🛍️',
    luckyColor: 'デイジーイエロー',
    advice: '小さくたたんでカバンにイン！急な荷物もへっちゃら。',
  },
  {
    id: 65,
    name: 'フリル付きポケットティッシュケース',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🧻',
    luckyColor: 'パウダーピンク',
    advice: '困っている友達にサッと差し出すと好感度大UP！',
  },
  {
    id: 66,
    name: 'ふんわり今治ミニタオル',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🧺',
    luckyColor: 'シェルホワイト',
    advice: '手を洗った後ふんわり拭くと清々しい気持ちに♪',
  },
  {
    id: 67,
    name: '花柄の折りたたみ傘',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '☂️',
    luckyColor: 'チェリーピンク',
    advice: '雨の日のお出かけも可愛い傘があればワクワク気分！',
  },
  {
    id: 68,
    name: 'ぷっくりネームタグ',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🏷️',
    luckyColor: 'キャンディオレンジ',
    advice: '自分の持ち物に愛着を持つと忘れ物知らずになれるよ。',
  },
  {
    id: 69,
    name: 'スマホ＆防犯ブザーショルダーストラップ',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '📱',
    luckyColor: 'パープル＆ピンク',
    advice: '斜めがけで両手フリー！身軽に行動できちゃうよ。',
  },
  {
    id: 70,
    name: 'クリアウォーターボトル',
    category: 'goods',
    categoryLabel: '持ち物',
    emoji: '🥤',
    luckyColor: 'クリアシトラス',
    advice: 'お気に入りのドリンクを入れてお出かけしよう！',
  },

  // 71-85: モチーフ＆ラッキーシンボル (15個)
  {
    id: 71,
    name: '四つ葉のクローバー',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🍀',
    luckyColor: 'エメラルドグリーン',
    advice: '奇跡の幸運を引き寄せる王道ラッキーシンボル！',
  },
  {
    id: 72,
    name: '流れ星モチーフ',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🌠',
    luckyColor: 'スターゴールド',
    advice: '心の中で3回お願いごとを唱えてみてね。',
  },
  {
    id: 73,
    name: 'ピンクのぷっくりハート',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '💕',
    luckyColor: 'ホットピンク',
    advice: '大好きな人や友達への思いやりが大きな幸運を呼ぶ！',
  },
  {
    id: 74,
    name: 'ユニコーンのマスコット',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🦄',
    luckyColor: 'パステルレインボー',
    advice: 'ファンタジーの世界のように不思議な良いことが起こりそう。',
  },
  {
    id: 75,
    name: '空にかかる七色の虹',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🌈',
    luckyColor: '七色（レインボー）',
    advice: '雨が止んだ後の青空のように希望に満ちた一日になるよ！',
  },
  {
    id: 76,
    name: '月と星のチャーム',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🌙',
    luckyColor: 'ミッドナイトブルー',
    advice: '夜空を見上げてリラックスすると直感力が高まるよ。',
  },
  {
    id: 77,
    name: 'ぷにぷに肉球スタンプ',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🐾',
    luckyColor: 'サーモンピンク',
    advice: '猫ちゃんのような気ままさと愛嬌でみんなをトリコに♪',
  },
  {
    id: 78,
    name: 'クラウン（王冠）モチーフ',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '👑',
    luckyColor: 'アンティークゴールド',
    advice: '堂々と胸を張って自信を持って発表してみて！',
  },
  {
    id: 79,
    name: '天使の羽モチーフ',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🪽',
    luckyColor: 'ピュアホワイト',
    advice: '優しい言葉をかけると、あなた自身も心が軽やかになれる。',
  },
  {
    id: 80,
    name: 'さくらんぼ（チェリー）柄',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🍒',
    luckyColor: 'チェリーレッド',
    advice: 'ふたつ並んだチェリーのように仲良しペアで大活躍！',
  },
  {
    id: 81,
    name: 'スマイリーフェイス',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '😊',
    luckyColor: 'ブライトイエロー',
    advice: 'あなたの笑顔が最高のラッキーチャームだよ！',
  },
  {
    id: 82,
    name: 'ダイヤモンドジュエル',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '💎',
    luckyColor: 'アクアマリン',
    advice: 'どんなときも自分らしさを磨き続けると輝けるよ。',
  },
  {
    id: 83,
    name: '青い鳥のマスコット',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🐦',
    luckyColor: 'スカイブルー',
    advice: '幸せはすぐ身近なところにあることに気づけそう。',
  },
  {
    id: 84,
    name: 'いちごモチーフ',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🍓',
    luckyColor: 'ストロベリーレッド',
    advice: '甘酸っぱい青春の思い出がいっぱい作れるかも！',
  },
  {
    id: 85,
    name: 'キラキラ魔法のステッキ',
    category: 'motif',
    categoryLabel: 'シンボル',
    emoji: '🪄',
    luckyColor: 'マジカルピンク',
    advice: '「きっとうまくいく！」と自分に魔法の言葉をかけてね。',
  },

  // 86-100: スタイル・アクション・気分 (15個)
  {
    id: 86,
    name: 'ふわふわハーフアップヘア',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '💇‍♀️',
    luckyColor: 'ハニーブラウン',
    advice: 'お嬢様気分のヘアスタイルで所作までキレイになれそう。',
  },
  {
    id: 87,
    name: '高め位置のすっきりポニーテール',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '👱‍♀️',
    luckyColor: 'アクティブオレンジ',
    advice: 'キュッと結べば気合い十分！スポーツや勉強がはかどるよ。',
  },
  {
    id: 88,
    name: '前髪くるんカーラー',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '✨',
    luckyColor: 'パステルピンク',
    advice: '理想の前髪が決まった日は一日中自信満々でいられる！',
  },
  {
    id: 89,
    name: 'ゆるふわ三つ編みツイン',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '👧',
    luckyColor: 'ナチュラルベージュ',
    advice: 'ちょっぴりレトロで可愛いスタイルがみんなに好評♪',
  },
  {
    id: 90,
    name: 'ロゴ入りベースボールキャップ',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '🧢',
    luckyColor: 'クラシックネイビー',
    advice: 'スポーティカジュアルで元気よくお出かけしよう！',
  },
  {
    id: 91,
    name: 'コットンバケットハット',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '👒',
    luckyColor: 'カーキグリーン',
    advice: 'こなれ感のあるトレンド帽子でおしゃれ上級者の仲間入り。',
  },
  {
    id: 92,
    name: 'お気に入りの白スニーカー',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '👟',
    luckyColor: 'ピュアホワイト',
    advice: 'ピカピカに磨いたスニーカーが良い場所へ連れて行ってくれる！',
  },
  {
    id: 93,
    name: 'ぷっくりピンクネイルチップ',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '💅',
    luckyColor: 'ミルキーピンク',
    advice: '休日は指先までドレスアップして特別気分を満喫してね。',
  },
  {
    id: 94,
    name: 'オーバーサイズパーカー',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '🧥',
    luckyColor: 'オートミールグレー',
    advice: 'ゆるっと着こなすリラックスコーデで居心地バツグン♪',
  },
  {
    id: 95,
    name: 'チェック柄プリーツスカート',
    category: 'action',
    categoryLabel: 'スタイル',
    emoji: '👗',
    luckyColor: 'バーガンディチェック',
    advice: '歩くたびに揺れるプリーツが知的でキュートな印象に！',
  },
  {
    id: 96,
    name: '鏡の前で笑顔の練習',
    category: 'action',
    categoryLabel: 'アクション',
    emoji: '🪞',
    luckyColor: 'サンシャインゴールド',
    advice: '最高の笑顔をチェックしてから出かけると大吉！',
  },
  {
    id: 97,
    name: '元気なあいさつ「おはよう！」',
    category: 'action',
    categoryLabel: 'アクション',
    emoji: '🗣️',
    luckyColor: 'ブライトオレンジ',
    advice: '一番大きな声であいさつすると周りの運気まで上がっちゃう！',
  },
  {
    id: 98,
    name: '帰り道のスキップ10歩',
    category: 'action',
    categoryLabel: 'アクション',
    emoji: '🏃‍♀️',
    luckyColor: 'ライトグリーン',
    advice: 'リズムに乗ってスキップするとモヤモヤも吹き飛ぶよ♪',
  },
  {
    id: 99,
    name: '深呼吸3回＆ストレッチ',
    category: 'action',
    categoryLabel: 'アクション',
    emoji: '🧘‍♀️',
    luckyColor: 'フォレストグリーン',
    advice: 'ゆっくり息を吸って吐くと、頭がスッキリ冴えわたるよ。',
  },
  {
    id: 100,
    name: '友達や家族へ「ありがとう」',
    category: 'action',
    categoryLabel: 'アクション',
    emoji: '💝',
    luckyColor: '愛のローズピンク',
    advice: '感謝の気持ちを言葉にすると、最高の幸運が返ってくるよ！',
  },
];
